# -*- coding: utf-8 -*-
# SPDX-License-Identifier: GPL-3.0-or-later
# Wasl - a verifiable nasab. Copyright (C) 2026 Hendra Saputra.
"""Hand-written summaries of the pinned biographical entries.

Everything else in this repository is quoted. A summary is not: it is the one place where
prose is composed rather than cited, which makes it the one place a plausible sentence could
pass unchecked. So a summary is not a paragraph here. It is an ordered list of lines, and an
`anchored` line carries the Arabic phrase from its own entry that it rests on. `validate.py`
re-reads that phrase out of the corpus and fails if it is not inside the pages the entry
claims - the same check every claim gets, applied sentence by sentence.

What that proves and what it does not: it proves each statement points at text that exists
where it says. It cannot prove the English is a fair rendering of the Arabic. That is a human
judgement, and Rule 6 is honest about it - the model drafts, the script decides what is real,
the human approves.

The rules the drafting follows:

* ANCHOR FIRST, SENTENCE SECOND. The dangerous failure is writing from memory: these lives
  are well known, and a fluent invented detail would read perfectly and anchor to nothing.
  Pull the phrase, then write to it.
* An `editorial` line rests on nothing quotable and is pure connective tissue. It may carry no
  number and no name, it is counted, and it is capped as a share of the whole.
* WHERE THE ENTRY DISAGREES WITH ITSELF, THE SUMMARY SAYS SO. Rule 3 applied to prose. Ibn
  Sa'd gives Safiyya's death as 50 and, in the same chapter, as 52; Ibn al-Athir reports five
  different counts of who preceded 'Umar into Islam. Smoothing that is editing the source.
* Nothing enters that is not in THIS entry, however well attested elsewhere.
"""

# who -> (work of the entry the summary reads, [(english, arabic anchor or None)])
SUMMARIES = {

 "Ṣafiyya bt. Ḥuyayy": ("IbnSad", [
  ("Ibn Saʿd opens on her descent: of the Children of Israel, of the line of Hārūn b. ʿImrān.",
   "من بني إسرائيل من سبط هارون بن عمران"),
  ("She had been married twice before — to Sallām b. Mishkam, who left her, then to Kināna b. "
   "al-Rabīʿ b. Abī al-Ḥuqayq, killed at Khaybar.",
   "وكانت صفية تزوجها سلام بن مشكم القرظي ثم فارقها، فتزوجها كنانة بن الربيع بن أبي الحقيق النضري فقتل عنها يوم خيبر"),
  ("How she came to the Prophet is told two ways in this one chapter, and neither is set aside.",
   None),
  ("In one she fell to Diḥya al-Kalbī in the division of the spoils,",
   "أن صفية بنت حيي وقعت في سهم دحية الكلبي"),
  ("and the Prophet bought her from him.",
   "فاشتراها رسول الله صلى الله عليه وسلم بسبعة آرس"),
  ("In the other she was simply among what he chose for himself at Khaybar.",
   "فكانت صفية مما اصطفى يوم خيبر"),
  ("He freed her and married her, and made her freedom her dower.",
   "فأعتقها وتزوجها وجعل عتقها مهرها"),
  ("Those present could not tell whether he had married her or taken her as a concubine,",
   "فقال الناس: والله ما ندري أتزوجها رسول الله صلى الله عليه وسلم أم تسرى بها"),
  ("until he veiled her and mounted her behind him — and then they knew.",
   "فلما حملها سترها وأردفها خلفه فعرف الناس أنه قد تزوجها"),
  ("She had dreamt of a moon coming from Yathrib until it fell into her lap.",
   "رأيت في المنام قمرا أقبل من يثرب حتى وقع في حجري"),
  ("Kināna struck her face for telling it, and the mark was still there when the Prophet asked.",
   "فقال: تحبين أن تكوني تحت هذا الملك الذي يأتي من المدينة؟ فضرب وجهي"),
  ("He told her that her father had been among the bitterest of the Jews against him.",
   "لم يزل أبوك من أشد يهود لي عداوة حتى قتله الله"),
  ("She answered him out of the Qurʾān: no bearer of burdens bears the burden of another.",
   "إن الله يقول في كتابه: {ولا تزر وازرة وزر أخرى}"),
  ("He put the choice to her — Islam and himself, or Judaism and her freedom —",
   "اختاري فإن اخترت الإسلام أمسكتك لنفسي وإن اخترت اليهودية فعسى أن أعتقك"),
  ("and she said God and His Messenger were dearer to her than being freed and going back.",
   "فالله ورسوله أحب إلي من العتق وأن أرجع إلى قومي"),
  ("His other wives called her the Jewess.",
   "وأزواج رسول الله صلى الله عليه وسلم ينظرن فقلن: أبعد الله اليهودية"),
  ("When ʿĀʾisha boasted over her, he told her what to answer: my father is Hārūn, my uncle Mūsā.",
   "ألا قلت أبي هارون وعمي موسى؟ وذلك أن عائشة فخرت عليها"),
  ("On one question the chapter contradicts itself outright, and both readings are left standing.",
   None),
  ("ʿAṭāʾ: the Messenger of God did not allot her a turn.",
   "كان رسول الله صلى الله عليه وسلم لا يقسم لصفية بنت حيي"),
  ("al-Zuhrī: she was one of his wives, and he allotted to her as he allotted to them.",
   "كانت صفية من أزواجه، وكان يقسم لها كما يقسم لنسائه"),
  ("She left a third of her estate to her sister's son, a Jew.",
   "أوصت لابن أختها، وهو يهودي بثلثها"),
  ("Her death is given here as the year fifty,",
   "وماتت صفية بنت حيي سنة خمسين في خلافة معاوية بن أبي سفيان"),
  ("and, in the closing line of the same chapter, as fifty-two — buried at al-Baqīʿ.",
   "وتوفيت صفية سنة اثنتين وخمسين في خلافة معاوية بن أبي سفيان وقبرت بالبقيع"),
 ]),

 "ʿUmar b. al-Khaṭṭāb": ("IbnAlAthir", [
  ("Ibn al-Athīr heads the entry with the full line and the kunya Abū Ḥafṣ.",
   "عمر بن الخطاب بن نفيل بن عبد العزي بن رياح بن عبد الله بن قرط بن رزاح ابن عدي بن كعب بن لؤي القرشي العدوي، أبو حفص"),
  ("His mother's name turns on one letter, and the entry sets the quarrel out rather than settling it.",
   None),
  ("Ḥantama daughter of Hāshim b. al-Mughīra —",
   "وأمه حنتمة بنت هاشم [1] بن المغيرة بن عبد الله بن عمر بن مخزوم"),
  ("or of Hishām, which would make her Abū Jahl's sister rather than his cousin.",
   "وقيل: حنتمة بنت هشام بن المغيرة، فعلى هذا تكون أخت أبي جهل، وعلى الأول تكون ابنة عمه"),
  ("Ibn ʿAbd al-Barr calls that reading a mistake;",
   "قال أبو عمر: ومن قال ذلك- يعني بنت هشام- فقد أخطأ"),
  ("Ibn Manda holds it, and makes Abū Jahl his uncle.",
   "وقال ابن منده: أم عمر أخت أبي جهل"),
  ("He was born thirteen years after the Elephant,",
   "ولد بعد الفيل بثلاث عشرة سنة"),
  ("though he reckoned it himself from the Fijār war instead.",
   "روي عن عمر أنه قال: ولدت بعد الفجار الأعظم بأربع سنين"),
  ("Before Islam he was Quraysh's envoy, sent when they had a quarrel to settle.",
   "وكان من أشرف قريش وإليه كانت السفارة في الجاهلية"),
  ("When Muḥammad was sent, ʿUmar was hard on him and on the Muslims.",
   "لما بعث الله محمدا صلى الله عليه وسلم، كان عمر شديدا عليه وعلى المسلمين"),
  ("How many had entered Islam before him is reported several ways on the same page.",
   None),
  ("Hilāl b. Yasāf: after forty men and eleven women.",
   "قال هلال بن يساف: أسلم عمر بعد أربعين رجلا وإحدى عشرة امرأة"),
  ("Or after thirty-nine men and twenty women, he completing the forty.",
   "وقيل: أسلم بعد تسعة وثلاثين رجلا وعشرين امرأة، فكمل الرجال به أربعين رجلا"),
  ("Saʿīd b. al-Musayyab: after forty men and ten women — and once he entered, Islam showed itself in Mecca.",
   "وقال سعيد بن المسيب: أسلم عمر بعد أربعين رجلا وعشر نسوة، فما هو إلا أن أسلم عمر فظهر الإسلام بمكة"),
  ("The Prophet had prayed: strengthen Islam with whichever of the two men You love better, ʿUmar or ʿAmr b. Hishām.",
   "اللهم أعز الإسلام بأحب الرجلين إليك: عمر بن الخطاب أو عمرو بن هشام"),
  ("By his own account he stood behind him in the mosque, heard him open Sūrat al-Ḥāqqa, and marvelled at how the Qurʾān was put together.",
   "فاستفتح سورة «الحاقة» فجعلت أعجب من تأليف القرآن"),
  ("He was the first to carry the whip, the first to gather people for the night prayer in Ramaḍān, the first to be called Commander of the Faithful.",
   "وهو أول من اتخذ الدرة، وأول من جمع الناس على قيام رمضان، وهو أول من سمي «أمير المؤمنين»"),
  ("His colour changed in the Year of Ashes because he forbade himself fat and milk until the people had plenty.",
   "وإنما تغير لونه عام الرمادة [5] لأنه أكثر أكل الزيت، لأنه حرم على نفسه السمن واللبن حتى يخصب الناس"),
  ("He was stabbed on a Wednesday, four nights left of Dhū al-Ḥijja, in the year twenty-three.",
   "طعن عمر يوم الأربعاء لأربع ليال بقين من ذي الحجة، سنة ثلاث وعشرين"),
  ("ʿUthmān b. Muḥammad al-Akhnasī answers flatly that this is a mistake.",
   "وقال عثمان بن محمد الأخنسي [5] : هذا وهم"),
  ("Ibn Qutayba has Abū Luʾluʾa strike him on a Monday; he lingered three days.",
   "وقال ابن قتيبة: ضربه أبو لؤلؤة يوم الأثنين لأربع بقين من ذي الحجة، ومكث ثلاثا، وتوفي"),
  ("He died at sixty-three, or at fifty-five — the entry prefers the first.",
   "وتوفي وهو ابن ثلاث وستين سنة، وقيل: كان عمره خمسا وخمسين سنة، والأول أصح"),
  ("Ṣuhayb prayed over him, and he was buried beside the Prophet and Abū Bakr.",
   "فصلى عليه صهيب، وقبر مع رسول الله صلى الله عليه وسلم وأبى بكر"),
 ]),

 "Quṣayy": ("IbnSad", [
  ("Fāṭima bt. Saʿd bore Kilāb b. Murra a son, Zuhra, and long after him a second, named Zayd.",
   "فولدت فاطمة بنت سعد لكلاب بن مرة زهرة بن كلاب، ثم مكثت دهرا، ثم ولدت قصيا فسمي زيدا"),
  ("Kilāb died, and Rabīʿa b. Ḥarām carried her off to his own country in Syria.",
   "وتوفي كلاب بن مرة، وقدم ربيعة بن حرام بن ضنة بن عبد بن كبير بن عذرة"),
  ("The child went with her, and was called Quṣayy for the distance she took him.",
   "وحملت قصيا معها لصغره وهو يومئذ فطيم، فسمي قصيا لتقصيها به إلى الشام"),
  ("A Quḍāʿī he had beaten at archery told him to go back where he belonged: you are not one of us.",
   "فقال رقيع: ألا تلحق ببلدك وقومك؟ فإنك لست منا"),
  ("His mother told him who his father was, and that his people were at Mecca beside the Sacred House.",
   "أبوك كلاب بن مرة بن كعب بن لؤي بن غالب بن فهر بن مالك بن النضر بن كنانة القرشي، وقومك بمكة عند البيت الحرام"),
  ("At Mecca he married Ḥubbā, daughter of Ḥulayl, who then held the keys of the House.",
   "خطب إلى حليل بن حبشية بن سلول بن كعب بن عمرو بن ربيعة، وهو لحي الخزاعي ابنته حبى"),
  ("How the House passed to him is given three ways, laid side by side without a choice between them.",
   None),
  ("He bought it from Ḥulayl's son for provisions — or, it is said, for a skin of wine.",
   "ثم اشترى منه البيت بأزواد، ويقال: بزق خمر"),
  ("Ḥulayl willed it to him, saying Quṣayy's children were his own daughter's.",
   "فأوصى بولاية البيت والقيام بأمر مكة إلى قصي، وقال: أنت أحق به"),
  ("Or he judged himself more entitled to it than Khuzāʿa and Bakr, and put it to the men of Quraysh.",
   "رأى أنه أولى بالبيت وأمر مكة من خزاعة وبني بكر"),
  ("He wrote to Rizāḥ, his brother by the same mother, to come and fight for him.",
   "وكتب قصي إلى أخيه ابن أمه رزاح بن ربيعة بن حرام العذري يدعوه إلى نصرته"),
  ("The arbitrator gave him the House and the rule of Mecca over Khuzāʿa,",
   "فقضى بينهم بأن قصي بن كلاب أولى بالبيت وأمر مكة من خزاعة"),
  ("and was named the Crusher, for the blood-claims he crushed underfoot.",
   "فسمي يومئذ يعمر الشداخ، لما شدخ من الدماء"),
  ("Quraysh, the entry says, were named that day for gathering to him.",
   "تجمعت إليه قريش، فسميت يومئذ قريشا لحال تجمعها، والتقرش: التجمع"),
  ("A second account in the same chapter derives the name quite differently, from the sons of Fihr.",
   "إنما سموا قريشا؛ لأن بني فهر الثلاثة كان اثنان منهم لأم"),
  ("He built the House of Assembly with its door facing the Kaʿba.",
   "فابتنى دار الندوة، وجعل بابها إلى البيت"),
  ("The doorkeeping, the watering, the provisioning, the war banner, the assembly and the judging of Mecca were all his.",
   "وكانت إليه الحجابة، والسقاية، والرفادة، واللواء، والندوة، وحكم مكة كله"),
  ("They called him the Gatherer for what he had gathered of their affairs.",
   "وسمته مجمعا لما جمع من أمرها"),
  ("All his children were Ḥubbā's: ʿAbd al-Dār his first-born, and ʿAbd Manāf, whose name was al-Mughīra.",
   "ولد لقصي بن كلاب ولده كلهم من حبى بنت حليل: عبد الدار بن قصي، وكان بكره، وعبد مناف بن قصي، واسمه المغيرة"),
  ("He said of them: four sons — two I named for my god, one for my house, one for myself.",
   "كان قصي يقول: ولد لي أربعة رجال، فسميت اثنين بإلهي، وواحدا بداري، وواحدا بنفسي"),
 ]),

 "Abū Bakr al-Ṣiddīq": ("IbnSad", [
  ("His name was ʿAbd Allāh; his father Abū Quḥāfa was ʿUthmān b. ʿĀmir, of Taym.",
   "واسمه: عبد الله بن أبي قحافة، واسمه: عثمان بن عامر بن عمرو بن كعب بن سعد بن تيم بن مرة"),
  ("His mother, Umm al-Khayr, was Salmā bt. Ṣakhr — of Taym as well.",
   "وأمه أم الخير, واسمها: سلمى بنت صخر بن عامر بن كعب بن سعد بن تيم بن مرة"),
  ("Ibn Isḥāq alone says the name ʿAtīq belonged to the father, and Ibn Saʿd notes that nobody else says it.",
   "وأما محمد بن إسحاق فقال: أبو قحافة, كان اسمه عتيقا، ولم يذكر ذلك غيره"),
  ("Ibrāhīm: the first to pray was Abū Bakr.",
   "عن إبراهيم, قال: أول من صلى أبو بكر الصديق"),
  ("His daughter Asmāʾ: my father was the first of the Muslims — I never knew him but holding this religion.",
   "قالت: أسلم أبي أول المسلمين، ولا والله ما عقلت أبي إلا وهو يدين الدين"),
  ("He entered Islam owning forty thousand dirhams,",
   "أسلم أبو بكر يوم أسلم وله أربعون ألف درهم"),
  ("and spent it freeing slaves and strengthening the Muslims until he reached Medina with five thousand.",
   "فكان يعتق منها ويقوي المسلمين, حتى قدم المدينة بخمسة آلاف درهم"),
  ("He was at Badr, Uḥud, the Trench and every engagement,",
   "وشهد أبو بكر: بدرا، وأحدا، والخندق، والمشاهد كلها مع رسول الله صلى الله عليه وسلم"),
  ("and among those who held their ground at Uḥud when the people turned.",
   "وكان في من ثبت مع رسول الله صلى الله عليه وسلم يوم أحد حين ولى الناس"),
  ("He died owing the treasury six thousand dirhams and left his orchard against it.",
   "توفي أبو بكر الصديق وعليه ستة آلاف كان أخذها من بيت المال"),
  ("To ʿĀʾisha: I have nothing but a milch-camel and a bowl — take them to ʿUmar when I die.",
   "يا عائشة، ما عندي من مال إلا لقحة وقدح، فإذا أنا مت, فاذهبوا بهما إلى عمر"),
  ("ʿUmar, receiving them: God have mercy on Abū Bakr, he has worn out whoever comes after him.",
   "فقال: يرحم الله أبا بكر، لقد أتعب من بعده"),
  ("On one thing the chapter reports two flatly opposed positions and settles neither.",
   None),
  ("ʿAlī: God have mercy on Abū Bakr — he was the first to gather the two boards.",
   "عن علي قال: يرحم الله أبا بكر، هو أول من جمع اللوحين"),
  ("Ibn Sīrīn: Abū Bakr died and did not gather the Qurʾān.",
   "عن محمد بن سيرين قال: مات أبو بكر ولم يجمع القرآن"),
  ("Saʿīd b. al-Musayyab: he completed in his caliphate the age of the Messenger of God, dying at sixty-three.",
   "استكمل أبو بكر في خلافته سن رسول الله صلى الله عليه وسلم، فتوفي وهو ابن ثلاث وستين سنة"),
  ("ʿĀʾisha: he died in the night and we buried him before morning.",
   "توفي أبو بكر ليلا, فدفناه قبل أن نصبح"),
  ("He had asked to be buried alongside the Prophet, and his head was set at the Prophet's shoulders.",
   "أوصى أبو بكر عائشة أن يدفن إلى جنب رسول الله صلى الله عليه وسلم"),
  ("ʿĀʾisha raised the wailing for him and ʿUmar came and forbade it.",
   "أقامت عليه عائشة النوح, فبلغ عمر, فجاء فنهاهن عن النوح على أبي بكر"),
  ("His father outlived him and inherited a sixth,",
   "ورث أبا بكر الصديق أبوه أبو قحافة السدس"),
  ("and when told, said only: a heavy loss — who has taken the command after him?",
   "قال: توفي ابنك، قال: رزء جليل، من قام بالأمر بعده؟"),
 ]),

 "ʿUthmān b. ʿAffān": ("IbnSad", [
  ("His mother was Arwā bt. Kurayz of ʿAbd Shams,",
   "وأمه أروى بنت كريز بن ربيعة بن حبيب بن عبد شمس بن عبد مناف بن قصي"),
  ("and her mother was Umm Ḥakīm al-Bayḍāʾ, daughter of ʿAbd al-Muṭṭalib.",
   "وأمها أم حكيم، وهي البيضاء بنت عبد المطلب بن هاشم بن عبد مناف بن قصي"),
  ("In the Jāhiliyya he was called Abū ʿAmr; the Muslims renamed him for the son Ruqayya bore him.",
   "وكان عثمان في الجاهلية يكنى أبا عمرو, فلما كان الإسلام ولد له من رقية بنت رسول الله صلى الله عليه وسلم غلام سماه: عبد الله, واكتنى به"),
  ("That child died at six, pecked on the eye by a cockerel.",
   "فبلغ عبد الله ست سنين فنقره ديك على عينه, فمرض فمات في جمادى الأولى سنة أربع من الهجرة"),
  ("When he entered Islam his uncle al-Ḥakam bound him: do you turn from the religion of your fathers to a new one?",
   "لما أسلم عثمان بن عفان أخذه عمه الحكم بن أبي العاص بن أمية, فأوثقه رباطا, وقال: أترغب عن ملة آبائك إلى دين محدث؟"),
  ("He made both migrations to Abyssinia with Ruqayya,",
   "فكان عثمان ممن هاجر من مكة إلى أرض الحبشة الهجرة الأولى والهجرة الثانية"),
  ("of whom the Prophet said: they are the first to migrate to God since Lot.",
   "إنهما لأول من هاجر إلى الله بعد لوط"),
  ("At the shūrā ʿAbd al-Raḥmān gave him his hand first, then ʿAlī.",
   "أول من بايع لعثمان عبد الرحمن, ثم علي بن أبي طالب"),
  ("He sent Ibn ʿAbbās to lead the pilgrimage in the year he was killed, thirty-five.",
   "استعمله على الحج في السنة التي قتل فيها سنة خمس وثلاثين"),
  ("Besieged, he answered the charge against him with the three things that make a Muslim's blood lawful, and said he was none of them.",
   "ما يحل دم امرئ مسلم, إلا رجل كفر بعد إيمانه، أو زنى بعد إحصانه، أو قتل رجلا فقتل به"),
  ("On the morning of his death he told a dream: the Messenger of God had said, ʿUthmān, break your fast with us.",
   "رأيت رسول الله صلى الله عليه وسلم البارحة، فقال لي: يا عثمان أفطر عندنا"),
  ("Kināna b. Bishr struck his forehead with an iron bar and he fell on his side.",
   "ضرب كنانة بن بشر جبينه ومقدم رأسه بعمود حديد فخر لجنبه"),
  ("al-Zuhrī puts the killing at the time of the afternoon prayer.",
   "قال: قتل عثمان عند صلاة العصر، وشد عبد لعثمان أسود على كنانة بن بشر فقتله"),
  ("His wife, after it: you killed him, and he used to keep the whole night alive with the Qurʾān in a single rakʿa.",
   "لقد قتلتموه وإنه ليحيي الليل كله بالقرآن في ركعة"),
  ("His treasurer held thirty million five hundred thousand dirhams on the day he died; it was plundered.",
   "كان لعثمان بن عفان عند خازنه يوم قتل ثلاثون ألف ألف درهم وخمسمئة ألف درهم"),
  ("He was the first to be buried in that ground.",
   "فكان عثمان بن عفان أول من دفن هناك"),
 ]),

 "ʿAlī b. Abī Ṭālib": ("IbnAlAthir", [
  ("Ibn al-Athīr heads him as the Prophet's paternal cousin.",
   "علي بن أبي طالب بن عبد المطلب بن هاشم بن عبد مناف بن قصي بن كلاب ابن مرة بن كعب بن لؤي القرشي الهاشمي. ابن عم رسول الله صلى الله عليه وسلم"),
  ("Abū Ṭālib's name was ʿAbd Manāf — or, it is said, his kunya was his name.",
   "واسم أبي طالب عبد مناف. وقيل: اسمه كنيته"),
  ("His mother was Fāṭima bt. Asad b. Hāshim.",
   "وأم علي فاطمة بنت أسد بن هاشم"),
  ("He was the first Hāshimī born of two Hāshimīs, and the first caliph of Banū Hāshim.",
   "وهو أول هاشمي ولد بين هاشميين، وأول خليفة من بني هاشم"),
  ("Who entered Islam first is argued through the entry rather than answered in it.",
   None),
  ("Mujāhid: ʿAlī became Muslim at ten.",
   "قال: أسلم علي وهو ابن عشر سنين"),
  ("al-Ḥasan and others: first after Khadīja, and at fifteen.",
   "أول من أسلم علي بعد خديجة، وهو ابن خمس عشرة سنة"),
  ("Zayd b. Arqam said ʿAlī was first — and Ibrāhīm al-Nakhaʿī, told of it, denied it: the first was Abū Bakr.",
   "فذكرت ذلك لإبراهيم النخعي، فأنكره وقال: «أول من أسلم أبو بكر»"),
  ("Abū Dharr, al-Miqdād, Khabbāb, Jābir and Abū Saʿīd all put him first after Khadīja.",
   "وقال أبو ذر والمقداد، وخباب، وجابر، وأبو سعيد الخدري، وغيرهم: إن عليا أول من أسلم بعد خديجة"),
  ("He was at Badr, Uḥud, the Trench and the Pledge, and at every engagement but Tabūk, where he was left over the Prophet's household.",
   "وشهد بدرا، وأحدا، والخندق، وبيعه الرضوان، وجميع المشاهد مع رسول الله صلى الله عليه وسلم إلا تبوك"),
  ("His feet were swollen and running with blood; the Prophet wept, spat on his hands and wiped them, and he never complained of them again.",
   "فتفل النبي صلى الله عليه وسلم في يديه، ومسح بهما رجليه، ودعا له بالعافية"),
  ("His own account of the caliphate: they gave me their hands willingly and unforced, then broke it.",
   "ثم إن عثمان قتل، فجاءوا فبايعوني طائعين غير مكرهين، ثم خلعوا بيعتي"),
  ("Ṭalḥa pledged first with his tongue and Saʿd with his hand.",
   "فكان أول من بايعه طلحة بلسانه، وسعد بيده"),
  ("Ibn Muljam's price for marrying Quṭām, whose father and brother ʿAlī had killed at Nahrawān, was that he avenge them.",
   "وكان علي قتل أباها وأخاها بالنهروان، فأعجبته فخطبها، فقالت: لا أتزوجك حتى تشتفي لي"),
  ("When ʿAlī was dead and buried, al-Ḥasan had Ibn Muljam brought out of prison to be killed.",
   "فلما مات علي ودفن بعث الحسن بن علي إلى ابن ملجم، فأخرجه من السجن ليقتله"),
  ("His age is disputed, and his son Ibn al-Ḥanafiyya reckoned by it that he had outlived his father.",
   "واختلفوا في عمره، فقال محمد بن الحنفية سنة الحجاف"),
 ]),

 "Muḥammad ﷺ": ("IbnAbdAlBarr", [
  ("Ibn ʿAbd al-Barr opens on the point this whole site turns on: the scholars of genealogy do not differ over the line up to ʿAdnān.",
   "لم يختلف أهل العلم بالأنساب والأخبار وسائر العلماء بالأمصار أنه صلى الله عليه وآله وسلم محمد بن عبد الله بن عبد المطلب"),
  ("Above ʿAdnān they do differ, and between Ibrāhīm and Sām b. Nūḥ, and he declines to set any of it down.",
   "واختلفوا فيما بين عدنان وإسماعيل بن إبراهيم عليهما السلام"),
  ("For the narrowing he quotes the Prophet: God chose Kināna of Ismāʿīl's children, and Quraysh of Kināna, and Banū Hāshim of Quraysh, and me of Banū Hāshim.",
   "إن الله اصطفى كنانة من ولد إسماعيل، واصطفى قريشا من كنانة، واصطفى من قريش بني هاشم، واصطفاني من بني هاشم"),
  ("Several names in the line are epithets. Hāshim was ʿAmr, called Hāshim for breaking bread for his people;",
   "واسم هاشم عمرو، وإنما قيل له هاشم، لأنه أول من هشم الثريد لقومه"),
  ("Quṣayy was Zayd, on the majority reading;",
   "واسم قصي زيد، هذا هو الأكثر"),
  ("ʿAbd Manāf, it is said, was al-Mughīra.",
   "وقد قيل اسم عبد مناف المغيرة، ويكنى أبا عبد شمس"),
  ("Of ʿAbd al-Muṭṭalib some say his name was ʿĀmir — Ibn ʿAbd al-Barr answers that this is not sound.",
   "وأما عبد المطلب فقيل أسمه عامر، ولا يصح والله أعلم"),
  ("Others say Shayba, and that he was called ʿAbd al-Muṭṭalib because his father Hāshim, dying, told his brother al-Muṭṭalib to fetch his boy from Yathrib.",
   "إنما قيل له عبد المطلب، لأن أباه هاشما قال لأخيه المطلب"),
  ("His mother was Āmina bt. Wahb, of Zuhra.",
   "أم رسول الله صلى الله عليه وآله وسلم آمنة بنت وهب ابن عبد مناف بن زهرة بن كلاب بن مرة، قرشية زهرية"),
  ("ʿAbd Allāh married her at thirty, or at twenty-five.",
   "تزوجها عبد الله ابن عبد المطلب، وهو ابن ثلاثين سنة، وقيل: بل كان يومئذ ابن خمس وعشرين سنة"),
  ("There is no disagreement that he was born in the Year of the Elephant,",
   "وقيل أنه ولد في شعب بني هاشم، ولا خلاف أنه ولد عام الفيل"),
  ("though one report puts it a month after the Elephant came.",
   "وقيل: ولد رسول الله صلى الله عليه وآله وسلم بعد قدوم الفيل بشهر"),
  ("The day is not disputed. Ibn ʿAbbās: your Prophet was born on a Monday, left Mecca on a Monday, entered Medina on a Monday, and Badr was a Monday.",
   "ولد نبيكم صلى الله عليه وآله وسلم يوم الاثنين، وحرج من مكة يوم الاثنين، ودخل المدينة يوم الاثنين، وكانت بدر يوم الاثنين"),
  ("The month is: two nights into Rabīʿ al-Awwal, or twelve.",
   "وقيل: لاثنتي عشرة ليلة خلت منه عام الفيل"),
  ("His father died while his mother was still carrying him.",
   "قال أبو عمر: ومات أبوه عبد الله بن عبد المطلب وأمه حامل به"),
 ]),

 "Khadīja": ("IbnAlAthir", [
  ("The first woman he married, and by the agreement of the Muslims the first of God's creation to enter Islam — no man and no woman before her.",
   "أول امرأة تزوجها، وأول خلق الله أسلم بإجماع المسلمين، لم يتقدمها رجل ولا امرأة"),
  ("al-Zubayr: in the Jāhiliyya she was called the Pure.",
   "قال الزبير: كانت تدعى في الجاهلية الطاهرة"),
  ("Her mother was Fāṭima bt. Zāʾida b. al-Aṣamm.",
   "وأمها فاطمة بنت زائدة بن الأصم"),
  ("She had been married before — to ʿAtīq b. ʿĀbid, who died leaving her a daughter, and then to Abū Hāla.",
   "وكانت- يعني خديجة- قبل النبي صلى الله عليه وسلم عند عتيق بن عابد بن عبد الله بن عمر بن مخزوم فولدت له جارية، وهلك عنها عتيق، فتزوجها أبو هالة"),
  ("The Prophet married her before the revelation, at twenty-five — or twenty-one — her uncle ʿAmr b. Asad giving her, her father being dead.",
   "وتزوج رسول الله صلى الله عليه وسلم خديجة- رضي الله عنها- قبل الوحي وعمره حينئذ خمس وعشرون سنة وقيل: إحدى وعشرون سنة، زوجها منه عمها عمرو بن أسد"),
  ("How many children she bore him is not settled, and Ibn al-Athīr lines the readings up.",
   "واختلف العلماء في أولاد رسول الله صلى الله عليه وسلم منها"),
  ("Some know of none but al-Qāsim and the four daughters.",
   "ما نعلمها ولدت له إلا القاسم وبناته الأربع"),
  ("Qatāda: two boys and four girls.",
   "وقال قتادة: ولدت له خديجة غلامين، وأربع بنات"),
  ("al-Zubayr: al-Qāsim the eldest, then Zaynab, then ʿAbd Allāh — who is called both al-Ṭayyib and al-Ṭāhir.",
   "وقال الزبير: ولدت لرسول الله صلى الله عليه وسلم القاسم وهو أكبر ولده ثم زينب ثم عبد الله وكان، يقال له الطيب، ويقال له الطاهر"),
  ("al-Kalbī has ʿAbd Allāh born in Islam and all the rest before it.",
   "وقال الكلبي: ولد عبد الله في الإسلام، وكل ولده منها ولد قبل الإسلام"),
  ("al-Qāsim, al-Ṭayyib and al-Ṭāhir died before Islam; the daughters lived to see it and migrated with him.",
   "فأما القاسم والطيب والطاهر فهلكوا قبل الإسلام، وبالقاسم كان يكنى رسول الله صلى الله عليه وسلم"),
  ("Ibn Isḥāq on what she was to him: she was the first to believe, and God lightened his burden through her — he never met a denial that she did not steady him after.",
   "وكانت خديجة أول من آمن بالله ورسوله، وصدق بما جاء به، فخفف الله بذلك عن رسول الله صلى الله عليه وسلم"),
  ("She died three days after Abū Ṭālib, in Ramaḍān, and was buried at al-Ḥajūn.",
   "قيل: إن وفاة خديجة كانت بعد أبي طالب بثلاثة أيام وكان موتها في رمضان، ودفنت بالحجون"),
 ]),

 "Fāṭima": ("IbnSad", [
  ("Her mother was Khadīja, and she was born while Quraysh were rebuilding the House, five years before the prophethood.",
   "وأمها خديجة بنت خويلد بن أسد بن عبد العزى بن قصي ولدتها وقريش تبني البيت وذلك قبل النبوة بخمس سنين"),
  ("Abū Bakr asked for her and was told to wait for the decree; ʿUmar asked and was told the same.",
   "أن أبا بكر خطب فاطمة إلى النبي صلى الله عليه وسلم فقال: يا أبا بكر انتظر بها القضاء"),
  ("Then: she is yours, ʿAlī — I am no liar; he had promised her to him already.",
   "فقال النبي صلى الله عليه وسلم: هي لك يا علي لست بدجال"),
  ("She and ʿAlī argued over which was older, and al-ʿAbbās settled it against her.",
   "وهي تقول: أنا أسن منك، فقال العباس: أما أنت يا فاطمة فولدت وقريش تبني الكعبة والنبي صلى الله عليه وسلم ابن خمس وثلاثين سنة"),
  ("In his last illness he told her she would be the first of his family to follow him and she wept, then asked whether she would not be content to be mistress of the women of this community — and she laughed.",
   "وقال: أنت أسرع أهلي بي لحوقا، قالت: فبكيت لذلك ثم قال: أما ترضين أن تكوني سيدة نساء هذه الأمة أو نساء العالمين؟ قالت: فضحكت"),
  ("She asked Abū Bakr for her inheritance and he answered with the Prophet's words — we leave no heir, what we leave is charity — and she was angry.",
   "فقال لها أبو بكر: إن رسول الله صلى الله عليه وسلم قال: لا نورث ما تركنا صدقة فغضبت فاطمة"),
  ("How long she outlived her father is given two ways in the same chapter: six months,",
   "وعاشت بعد وفاة رسول الله صلى الله عليه وسلم ستة أشهر"),
  ("and, on Abū Jaʿfar's authority, three.",
   "قال: توفيت فاطمة بعد النبي صلى الله عليه وسلم بثلاثة أشهر"),
  ("Hers was the first bier of its kind, made for her by Asmāʾ bt. ʿUmays, who had seen the like in Abyssinia.",
   "قال: فاطمة أول من جعل لها النعش عملته لها أسماء بنت عميس وكانت قد رأته يصنع بأرض الحبشة"),
  ("al-Zuhrī: she was buried at night, and ʿAlī buried her.",
   "قال: دفنت فاطمة بنت رسول الله صلى الله عليه وسلم ليلا ودفنها علي"),
 ]),

 "Ḥamza": ("IbnSad", [
  ("Ibn Saʿd heads him: the Lion of God, the Lion of His Messenger, and his uncle.",
   "أسد الله، وأسد رسوله، وعمه رضي الله عنه, ابن عبد المطلب بن هاشم بن عبد مناف بن قصي"),
  ("His mother was Hāla bt. Uhayb, of Zuhra — so he and the Prophet's mother were of one clan.",
   "وأمه هالة بنت أهيب بن عبد مناف بن زهرة بن كلاب بن مرة، وكان يكنى أبا عمارة"),
  ("He entered Islam in anger: hearing Abū Jahl had abused the Prophet, he came into the mosque and split his head with a bow.",
   "فدخل المسجد مغضبا, فضرب رأس أبي جهل بالقوس ضربة أوضحت في رأسه، وأسلم حمزة"),
  ("It was the sixth year of the prophethood, and the Prophet and the Muslims were strengthened by him.",
   "فعز به رسول الله صلى الله عليه وسلم والمسلمون، وذلك بعد دخول رسول الله صلى الله عليه وسلم دار الأرقم, في السنة السادسة من النبوة"),
  ("Waḥshī b. Ḥarb killed him at Uḥud and cut him open; Hind bt. ʿUtba chewed his liver and spat it out,",
   "قتله وحشي بن حرب, وشق بطنه، وأخذ كبده، فجاء بها إلى هند بنت عتبة بن ربيعة فمضغتها، ثم لفظتها"),
  ("then made bracelets and anklets of what she took, and carried them to Mecca.",
   "ثم جاءت فمثلت بحمزة، وجعلت من ذلك مسكتين، ومعضدين، وخدمتين، حتى قدمت بذلك وبكبده مكة"),
  ("His sister Ṣafiyya came looking for him and ʿAlī and al-Zubayr each pressed the other to tell her.",
   "أقبلت صفية تطلبه لا تدري ما صنع، قال: فلقيت عليا, والزبير، فقال علي للزبير: اذكر لأمك"),
  ("The Prophet feared for her reason, put his hand on her breast and prayed, and she wept.",
   "فقال: إني أخاف على عقلها، قال: فوضع يده على صدرها ودعا لها، فاسترجعت وبكت"),
  ("Standing over the mutilated body: were it not for the women's grief I would leave him to be gathered from the crops of birds and the bellies of beasts.",
   "فقام عليه وقد مثل به, فقال: لولا جزع النساء لتركته حتى يحشر من حواصل الطير وبطون السباع"),
  ("Abū Bakr, ʿUmar, ʿAlī and al-Zubayr went down into his grave while the Prophet sat at its edge.",
   "ونزل في قبر حمزة: أبو بكر, وعمر, وعلي, والزبير، ورسول الله صلى الله عليه وسلم جالس على حفرته"),
  ("He said he had seen the angels washing Ḥamza, and Ḥamza was the first of that day's martyrs he prayed over, with four takbīrs.",
   "رأيت الملائكة تغسل حمزة, لأنه كان جنبا ذلك اليوم، وكان حمزة أول من صلى رسول الله صلى الله عليه وسلم عليه ذلك اليوم من الشهداء، وكبر عليه أربعا"),
 ]),

 "al-Ḥasan": ("IbnSad", [
  ("Son of ʿAlī and of Fāṭima, and so grandson of Khadīja on his mother's side.",
   "ابن أبي طالب بن عبد المطلب بن هاشم بن عبد مناف بن قصي, وأمه فاطمة بنت رسول الله صلى الله عليه وسلم, وأمها خديجة بنت خويلد بن أسد بن عبد العزى بن قصي"),
  ("Born in the middle of Ramaḍān, year three.",
   "قال محمد بن عمر: ولد الحسن بن علي بن أبي طالب في النصف من شهر رمضان, سنة ثلاث من الهجرة"),
  ("ʿAlī: I loved war, and meant to name him Ḥarb — the Messenger of God named him al-Ḥasan.",
   "قال: قال علي: كنت رجلا أحب الحرب, فلما ولد الحسن, هممت أن أسميه حربا, فسماه رسول الله صلى الله عليه وسلم الحسن"),
  ("And of the second: I named these two sons of mine after Hārūn's sons, Shabbar and Shubayr.",
   "وسماه رسول الله صلى الله عليه وسلم الحسين وقال: إني سميت ابني هذين باسمي ابني هارون شبرا وشبيرا"),
  ("Abū Saʿīd al-Khudrī reports the Prophet: al-Ḥasan and al-Ḥusayn are the two lords of the youth of Paradise.",
   "قال رسول الله صلى الله عليه وسلم: حسن, وحسين سيدا شباب أهل الجنة"),
  ("ʿAlī: al-Ḥasan was likest the Messenger of God from the chest to the head.",
   "عن علي, قال: الحسن أشبه رسول الله صلى الله عليه وسلم, ما بين الصدر إلى الرأس"),
  ("Dying, he pressed his brother: do not let blood be spilt over me, the people are quick to strife.",
   "وجعل الحسن يوعز إلى الحسين يا أخي: إياك أن تسفك الدماء في، فإن الناس سراع إلى الفتنة"),
  ("He asked to be buried with the Prophet — and that if he were prevented, and a cupping-glass of blood were feared over it, he be buried with his mother at al-Baqīʿ instead.",
   "عهد أن يدفن مع رسول الله صلى الله عليه وسلم إن استطيع ذلك، فإن حيل بينه وبينه، وخيف أن يهراق فيه محجم من دم, دفن مع أمه بالبقيع"),
  ("When he died Medina shook with the cry of it, and you met nobody who was not weeping.",
   "فلما توفي الحسن, ارتجت المدينة صياحا, فلا يلقى أحد إلا باكيا"),
 ]),

 "al-Ḥusayn": ("IbnSad", [
  ("Son of ʿAlī, called Abū ʿAbd Allāh.",
   "ابن علي بن أبي طالب بن عبد المطلب بن هاشم بن عبد مناف بن قصي، ويكنى: أبا عبد الله"),
  ("His mother was Fāṭima, and hers was Khadīja — the wording is all but identical to al-Ḥasan's entry a few pages earlier.",
   "ويكنى: أبا عبد الله. وأمه فاطمة بنت رسول الله صلى الله عليه وسلم"),
  ("Ibn Saʿd dates the conception: five nights into Dhū al-Qaʿda of year three, fifty nights after al-Ḥasan's birth, and the birth in Shaʿbān of year four.",
   "علقت فاطمة رضي الله عنها بالحسين, لخمس ليال خلون من ذي القعدة, سنة ثلاث من الهجرة، فكان بين ذلك وبين ولاد الحسن خمسون ليلة، وولد الحسين في ليال خلون من شعبان, سنة أربع من الهجرة"),
  ("Umm al-Faḍl asked to nurse him, brought him to the Prophet, and he wet his waist-wrapper; he told her a boy's water is poured over and a girl's washed.",
   "قلت: يا رسول الله, أعطنيه, أو ادفعه إلي فلأكفله وأرضعه بلبن قثم، ففعل، فأتيته به، فوضعه على صدره، فبال عليه"),
  ("On the road he woke saying he had dreamt of a horseman keeping pace with them: the people travel, and the deaths travel towards them.",
   "إني رأيت في المنام آنفا فارسا يسايرنا, ويقول: القوم يسرون, والمنايا تسري إليهم"),
  ("He knew it for a death-notice, and rode on until he halted at Karbalāʾ.",
   "فعلمت أنه نعي إلينا أنفسنا، ثم سار, حتى نزل بكربلاء"),
  ("His eldest son ʿAlī was killed with him at al-Ṭaff and left no line.",
   "فولد الحسين: عليا الأكبر، قتل مع أبيه بالطف, لا بقية له"),
  ("The Prophet: al-Ḥusayn is of me and I am of him — God love whoever loves al-Ḥusayn.",
   "قال: حسين مني وأنا منه، أحب الله من أحب حسينا، حسين سبط من الأسباط"),
  ("ʿAlī counted him the likest of his family to himself, and said al-Ḥasan would step out of the command.",
   "وابني هذا، يعني الحسن، سيخرج من هذا الأمر, وأشبه أهلي بي الحسين"),
  ("When Muʿāwiya took the people's pledge for Yazīd, al-Ḥusayn was among those who did not give it.",
   "لما بايع معاوية بن أبي سفيان الناس ليزيد بن معاوية، كان حسين بن علي بن أبي طالب ممن لم بايع له"),
  ("The people of Kūfa had been writing to him to come out to them since Muʿāwiya's time, and each time he refused.",
   "وكان أهل الكوفة يكتبون إلى حسين, يدعونه إلى الخروج إليهم في خلافة معاوية، كل ذلك يأبى"),
  ("Muslim b. ʿAqīl's last message was to turn him back: the people have deceived him and lied to him.",
   "فإن القوم غروه وخدعوه وكذبوه، وإنه إن قتل لم يكن لبني هاشم بعده نظام"),
  ("A man who went to look afterwards found his body, and his companions lying in a ring around him.",
   "فانتهينا إلى المكان، وإذا جسد الحسين على رجل الحمار, وإذا أصحابه ربضة حوله"),
  ("They found thirty-three wounds on him, and in his garment a hundred and some rents from arrows and blows. He was killed on a Friday, the day of ʿĀshūrāʾ, in Muḥarram of the year sixty-one, aged fifty-six years and five months.",
   "ووجدوا بالحسين ثلاثا وثلاثين جراحة، ووجدوا في ثوبه مائة وبضعة عشر خرقا من السهام وأثر الضرب، وقتل يوم الجمعة, يوم عاشوراء, في المحرم, سنة إحدى وستين، وله يومئذ ست وخمسون سنة, وخمسة أشهر"),
 ]),

 "al-ʿAbbās": ("IbnSad", [
  ("His mother was Nutayla bt. Janāb, of al-Namir b. Qāsiṭ — not a Qurashī woman.",
   "وأم العباس نتيلة بنت جناب بن كليب بن مالك بن عمرو بن عامر بن زيد مناة بن عامر"),
  ("His son Ibn ʿAbbās: my father was born three years before the men of the Elephant came, and was three years older than the Messenger of God.",
   "ولد أبي العباس بن عبد المطلب قبل قدوم أصحاب الفيل بثلاث سنين، وكان أسن من رسول الله صلى الله عليه وسلم بثلاث سنين"),
  ("When al-Aws and al-Khazraj argued over who first struck the Prophet's hand at al-ʿAqaba, they asked al-ʿAbbās, who said nobody knew it better than he did.",
   "تفاخرت الأوس والخزرج فيمن ضرب على يد رسول الله صلى الله عليه وسلم ليلة العقبة أول الناس, فقالوا: لا أحد أعلم به من العباس بن عبد المطلب"),
  ("Taken at Badr, he ransomed himself and his nephew ʿAqīl for eighty ounces of gold — or, it is said, a thousand dīnārs.",
   "فدى العباس نفسه وابن أخيه عقيلا بثمانين أوقية ذهب، ويقال: ألف دينار"),
  ("He, Nawfal and ʿAqīl were sent back to Mecca to keep up the watering and the provisioning, which had been Banū Hāshim's since the Jāhiliyya.",
   "وذكر أن العباس, ونوفلا, وعقيلا رجعوا إلى مكة, أمروا بذلك ليقيموا ما كانوا يقيمون من أمر السقاية والرفادة والرئاسة"),
  ("The Prophet, pressed about his alms: a man's uncle is his father's twin — al-ʿAbbās paid us this year's zakāt a year early.",
   "فقال صلى الله عليه وسلم: تربت يداك, أما علمت أن عم الرجل صنو أبيه، إن العباس سلفنا زكاة العام عام أول"),
  ("In drought under ʿUmar he was brought out to pray for rain: we used to ask through Your Prophet, and now we ask through Your Prophet's uncle.",
   "أنهم كانوا إذا قحطوا على عهد عمر خرج بالعباس، فاستسقى به"),
  ("He died on a Friday, fourteen nights into Rajab of the year thirty-two, aged eighty-eight, and was buried at al-Baqīʿ in the burial-ground of Banū Hāshim.",
   "وتوفي العباس يوم الجمعة, لأربع عشرة خلت من رجب, سنة اثنتين وثلاثين في خلافة عثمان بن عفان، وهو ابن ثمان وثمانين سنة، ودفن بالبقيع في مقبرة بني هاشم"),
 ]),

 "Jaʿfar b. Abī Ṭālib": ("IbnSad", [
  ("Brother of ʿAlī by the same mother, Fāṭima bt. Asad.",
   "وأمه فاطمة بنت أسد بن هاشم بن عبد مناف بن قصي، وكان لجعفر من الولد: عبد الله, وبه كان يكنى"),
  ("His three sons — ʿAbd Allāh, ʿAwn and Muḥammad — were all born to him in Abyssinia during the migration there.",
   "ومحمد وعون لا عقب لهما، ولدوا جميعا لجعفر بأرض الحبشة في المهاجر إليها"),
  ("Their mother was Asmāʾ bt. ʿUmays, who later married Abū Bakr and then ʿAlī: her sons by the three were half-brothers.",
   "ولد جعفر بن أبي طالب: عبد الله، وعون، ومحمد بنو جعفر، وأخواهم لأمهم يحيى بن علي بن أبي طالب، ومحمد بن أبي بكر"),
  ("An eyewitness at Muʾta: I can still see Jaʿfar dismounting from a sorrel mare and hamstringing her, then fighting until he was killed.",
   "كأني أنظر إلى جعفر بن أبي طالب يوم مؤتة, نزل عن فرس له شقراء فعقرها، ثم قاتل حتى قتل"),
  ("He was killed at al-Balqāʾ on the day of Muʾta, and the Prophet prayed: God, take Jaʿfar's place in his family.",
   "قتل جعفر بن أبي طالب بالبلقاء يوم مؤتة، فقال رسول الله صلى الله عليه وسلم: اللهم اخلف جعفرا في أهله"),
 ]),

 "Zaynab bt. Muḥammad": ("IbnSad", [
  ("Khadīja's daughter, and the eldest of the Prophet's daughters.",
   "وأمها خديجة بنت خويلد بن أسد بن عبد العزى بن قصي، وكانت أكبر بنات رسول الله صلى الله عليه وسلم"),
  ("She married her mother's sister's son, Abū al-ʿĀṣ b. al-Rabīʿ, before the prophethood — the first of the daughters to marry.",
   "تزوجها ابن خالتها أبو العاص بن الربيع بن عبد العزى بن عبد شمس بن عبد مناف بن قصي قبل النبوة وكانت أول بنات رسول الله صلى الله عليه وسلم تزوج"),
  ("His mother Hāla bt. Khuwaylid was Khadīja's sister, and so Zaynab's aunt.",
   "وأم أبي العاص هالة بنت خويلد بن أسد بن عبد العزى بن قصي خالة زينب بنت رسول الله صلى الله عليه وسلم"),
  ("She bore him ʿAlī, who died young, and Umāma.",
   "وولدت زينب لأبي العاص عليا، وأمامة امرأة، فتوفي علي وهو صغير"),
  ("She entered Islam and migrated with her father while her husband was still in Syria and still a pagan.",
   "قدم أبو العاص بن الربيع من الشام، وقد أسلمت امرأته زينب مع أبيها وهاجرت ثم أسلم بعد ذلك وما فرق بينهما"),
  ("Later she gave him protection, and the Prophet upheld it: the believers are one hand against all others, and the least of them may grant protection.",
   "المؤمنون يد على من سواهم يجير عليهم أدناهم وقد أجرنا من أجارت"),
  ("She asked that what had been taken from him be returned, and he ordered it — but told her he could not come near her while he remained a pagan.",
   "فسألته أن يرد على أبي العاص ما أخذ منه ففعل وأمرها أن لا يقربها فإنها لا تحل له ما دام مشركا"),
  ("Qatāda: she migrated with her father, then her husband became Muslim and migrated after her, and the Prophet returned her to him.",
   "أن زينب بنت رسول الله صلى الله عليه وسلم كانت تحت أبي العاص بن الربيع فهاجرت مع رسول الله صلى الله عليه وسلم ثم أسلم زوجها فهاجر إلى رسول الله صلى الله عليه وسلم فردها عليه"),
 ]),

 "Ibrāhīm b. Muḥammad": ("IbnSad", [
  ("Ibn Saʿd puts his story where it starts: the letter carried to the Muqawqis of Alexandria after al-Ḥudaybiya, in Dhū al-Qaʿda of year six.",
   "لما رجع رسول الله صلى الله عليه وسلم من الحديبية في ذي القعدة سنة ست من الهجرة بعث حاطب بن أبي بلتعة إلى المقوقس القبطي صاحب الإسكندرية"),
  ("Anas: when Ibrāhīm was born Jibrīl came and greeted him — peace be upon you, father of Ibrāhīm.",
   "قال: لما ولد إبراهيم جاء جبريل إلى رسول الله صلى الله عليه وسلم، فقال: السلام عليك يا أبا إبراهيم"),
  ("He came out in the morning and said: a boy was born to me last night, and I have named him with my father's name, Ibrāhīm.",
   "قال: إنه ولد لي الليلة غلام، وإني سميته باسم أبي إبراهيم"),
  ("He brought him to ʿĀʾisha: look how like me he is. She saw no likeness. He said: do you not see his whiteness and his flesh?",
   "قالت: لما ولد إبراهيم جاء به رسول الله صلى الله عليه وسلم إلي فقال: انظري إلى شبهه بي"),
  ("At his death: the heart will grieve and the eye will weep, and we will not say what angers the Lord.",
   "إن القلب سيحزن، وإن العين ستدمع, ولن نقول ما يسخط الرب"),
  ("And: were it not for an appointed term and a known hour, our grief for you would be harder than it is — we are grieved for you, Ibrāhīm.",
   "لولا أنه أجل معدود، ووقت معلوم لجزعنا عليك أشد مما جزعنا"),
  ("Qatāda adds the words: the rest of his suckling is in the Garden.",
   "وإنا عليك يا إبراهيم لمحزونون وقال: تمام رضاعه في الجنة"),
  ("And: Ibrāhīm is my son, and he died at the breast, and he has two nurses who will finish his suckling in the Garden.",
   "إن إبراهيم ابني، وإنه مات في الثدي، وإن له لظئرين تكملان رضاعه في الجنة"),
 ]),

 "ʿĀʾisha bt. Abī Bakr": ("IbnAlAthir", [
  ("Ibn al-Athīr heads her the truthful daughter of the truthful, and the best known of his wives.",
   "عائشة بنت أبي بكر الصديق، الصديقة بنت الصديق أم المؤمنين، زوج النبي صلى الله عليه وسلم وأشهر نسائه"),
  ("Her mother was Umm Rūmān, of Kināna.",
   "وأمها أم رومان ابنة عامر بن عويمر بن عبد شمس"),
  ("He married her two years before the Hijra, on Abū ʿUbayda's reckoning — or three.",
   "تزوجها رسول الله صلى الله عليه وسلم قبل الهجرة بسنتين، وهي بكر، قاله أبو عبيدة. وقيل: بثلاث سنين"),
  ("Her age at the marriage is given as six, and as seven.",
   "وكان عمرها لما تزوجها رسول الله صلى الله عليه وسلم ست سنين، وقيل: سبع سنين"),
  ("When the Prophet died she was eighteen.",
   "ولما توفي النبي صلى الله عليه وسلم كان عمرها ثمان عشرة سنة"),
  ("ʿUrwa: I never saw anyone better versed in law, or medicine, or poetry than ʿĀʾisha — and had she nothing but the affair of the slander, that alone would be honour enough, for Qurʾān came down about her that is recited to the Day of Rising.",
   "وقال عروة: ما رأيت أحدا أعلم بفقه ولا بطب ولا بشعر من عائشة، ولو لم يكن لعائشة من الفضائل إلا قصة الإفك لكفى بها فضلا وعلو مجد"),
  ("Anas reports the Prophet: ʿĀʾisha's excellence over women is that of tharīd over other food.",
   "قال رسول الله صلى الله عليه وسلم: فضل عائشة على النساء كفضل الثريد على سائر الطعام"),
  ("The senior Companions asked her on the law of inheritance, and ʿAṭāʾ called her the soundest of people in public judgement.",
   "وكان أكابر الصحابة يسألونها عن الفرائض، وقال عطاء بن أبي رباح: كانت عائشة من أفقه الناس وأحسن الناس رأيا في العامة"),
  ("Masrūq, when he transmitted from her, would say: the truthful daughter of the truthful told me, the innocent, the vindicated.",
   "وكان مسروق إذا روى عنها يقول: حدثتني الصديقة بنت الصديق، البريئة المبرأة"),
  ("She was buried at al-Baqīʿ by night as she had asked, Abū Hurayra praying over her and five of her kin going down into the grave.",
   "وأمرت أن تدفن بالبقيع ليلا، فدفنت وصلى عليها أبو هريرة، ونزل في قبرها خمسة"),
 ]),

 "Sawda bt. Zamʿa": ("IbnSad", [
  ("Her mother, al-Shamūs bt. Qays, was of the Anṣār, of Banū ʿAdī b. al-Najjār.",
   "وأمها الشموس بنت قيس بن عمرو بن زيد بن لبيد بن خداش بن عامر بن غنم بن عدي بن النجار، من الأنصار"),
  ("She had married al-Sakrān b. ʿAmr; both entered Islam early at Mecca and both went out to Abyssinia in the second migration.",
   "تزوجها السكران بن عمرو بن عبد شمس بن عبد ود بن نصر بن مالك بن حسل بن عامر بن لؤي، وأسلمت بمكة قديما، وبايعت، وأسلم زوجها السكران بن عمرو، وخرجا جميعا مهاجرين إلى أرض الحبشة في الهجرة الثانية"),
  ("Widowed at Mecca, she had Ḥāṭib b. ʿAmr marry her to the Prophet: the first woman he married after Khadīja.",
   "فأمرت حاطب بن عمرو بن عبد شمس بن عبد ود فزوجها، فكانت أول امرأة تزوجها رسول الله صلى الله عليه وسلم بعد خديجة"),
  ("He said to her once: count your waiting-period.",
   "قال رسول الله صلى الله عليه وسلم لسودة بنت زمعة: اعتدي"),
  ("ʿĀʾisha: Sawda gave her day and her night to me, seeking by it the Messenger of God's contentment.",
   "أن سودة وهبت يومها وليلتها لعائشة تبتغي بذلك رضا رسول الله صلى الله عليه وسلم"),
  ("Her portion of Khaybar was eighty loads of dates and twenty of barley — or of wheat.",
   "أطعم رسول الله صلى الله عليه وسلم سودة بنت زمعة بخيبر ثمانين وسقا تمرا وعشرين وسقا شعيرا، قال: ويقال: قمح"),
  ("She died at Medina in Shawwāl of the year fifty-four.",
   "توفيت سودة بنت زمعة بالمدينة في شوال سنة أربع وخمسين في خلافة معاوية بن أبي سفيان"),
 ]),

 "Ḥafṣa bt. ʿUmar": ("IbnSad", [
  ("Her mother was Zaynab bt. Maẓʿūn, sister of ʿUthmān b. Maẓʿūn.",
   "وأمها زينب بنت مظعون (1) بن حبيب بن وهب بن حذافة بن جمح أخت عثمان بن مظعون"),
  ("ʿUmar: Ḥafṣa was born while Quraysh were building the House, five years before the Prophet was sent.",
   "قال: ولدت حفصة وقريش تبني البيت قبل مبعث النبي صلى الله عليه وسلم بخمس سنين"),
  ("She had been married to Khunays b. Ḥudhāfa, migrated with him, and was widowed after Badr.",
   "تزوج خنيس بن حذافة بن قيس بن عدي بن سعد بن سهم حفصة بنت عمر بن الخطاب فكانت عنده وهاجرت معه إلى المدينة فمات عنها بعد الهجرة مقدم النبي صلى الله عليه وسلم من بدر"),
  ("Anas: when the Prophet divorced Ḥafṣa he was commanded to take her back, and he took her back.",
   "أن النبي صلى الله عليه وسلم لما طلق حفصة أمر أن يراجعها فراجعها"),
  ("The reason given: Jibrīl came and said, take Ḥafṣa back, for she fasts much and stands much in prayer, and she is your wife in the Garden.",
   "إن جبريل صلى الله عليه وسلم أتاني فقال لي أرجع حفصة فإنها صوامة قوامة وهي زوجتك في الجنة"),
  ("She was party to the trick of the honey, agreed between the wives to make him think a smell displeased him.",
   "فإنه سيقول لك سقتني حفصة شربة عسل فقولي: جرست نحله العرفط"),
  ("Her portion of Khaybar was eighty loads of barley — or of wheat.",
   "وأطعم رسول الله صلى الله عليه وسلم حفصة ثمانين وسقا شعيرا ويقال: قمح"),
  ("Marwān b. al-Ḥakam, then governor of Medina, prayed over her.",
   "توفيت حفصة فصلى عليها مروان بن الحكم، وهو يومئذ عامل المدينة"),
 ]),

 "Umm Salama (Hind)": ("IbnSad", [
  ("Her name was Hind, daughter of Abū Umayya — whose own name was Suhayl, called Zād al-Rakb — of Makhzūm.",
   "واسمها هند بنت أبي أمية واسمه سهيل زاد الركب بن المغيرة بن عبد الله بن عمر بن مخزوم"),
  ("She had married Abū Salama and gone with him to Abyssinia in both migrations, bearing him children there.",
   "تزوجها أبو سلمة اسمه عبد الله بن عبد الأسد بن هلال بن عبد الله بن عمر بن مخزوم وهاجر بها إلى أرض الحبشة في الهجرتين جميعا"),
  ("Abū Salama, dying, told her to marry after him, and prayed: God, grant Umm Salama after me a man better than I am, who will not grieve her or wrong her.",
   "قال: فإذا مت فتزوجي ثم قال: اللهم ارزق أم سلمة بعدي رجلا خيرا مني لا يحزنها ولا يؤذيها"),
  ("She had learnt the words for a calamity from the Prophet himself — God reward me in my affliction and give me better after it —",
   "من أصيب بمصيبة فقال كما أمره الله {إنا لله وإنا إليه راجعون} اللهم آجرني في مصيبتي وأعقبني خيرا منها فعل الله ذلك به"),
  ("and balked at saying it: who is better than Abū Salama? She said it, and afterwards said God had hurried the answer.",
   "فعجل فقلتها يوم توفي أبو سلمة ثم قلت: ومن لي مثل أبي سلمة فعجل الله لي الخلف خيرا من أبي سلمة"),
  ("When the Prophet asked for her she raised three objections: I am old, I have children, and I am a jealous woman.",
   "قالت: في خصال ثلاث أما أنا فكبيرة وأنا مطفل وأنا غيور"),
  ("He answered each: the jealousy we will ask God to take from you, as for age I am older than you, and the children are God's affair and His Messenger's.",
   "فقال: أما ما ذكرت من الغيرة فندعو الله حتى يذهبه عنك وأما ما ذكرت من الكبر فأنا أكبر منك والطفل إلى الله وإلى رسوله"),
  ("Abū Jaʿfar: he came to her when Abū Salama died and spoke to her so long, leaning on his hand, that the matting marked it.",
   "أن رسول الله صلى الله عليه وسلم دخل على أم سلمة حين توفي أبو سلمة فذكر ما أعطاه الله وما قسم له وما فضله فما زال يذكر ذلك ويتحامل على يده حتى أثر الحصير في يده مما يحدثها"),
 ]),

 "Zaynab bt. Khuzayma": ("IbnSad", [
  ("Of Banū Hilāl b. ʿĀmir b. Ṣaʿṣaʿa, and called Mother of the Poor already in the Jāhiliyya.",
   "بن عامر بن صعصعة وهي أم المساكين كانت تسمى بذلك في الجاهلية"),
  ("al-Zuhrī: Zaynab bt. Khuzayma al-Hilāliyya was called Mother of the Poor, and had been married to al-Ṭufayl b. al-Ḥārith, who divorced her.",
   "كانت زينب بنت خزيمة الهلالية تدعى أم المساكين وكانت عند الطفيل بن الحارث بن المطلب بن عبد مناف فطلقها"),
  ("Ibn Saʿd's own informant continues: then ʿUbayda married her — the chapter given her is barely a page.",
   "فحدثني عبد الله بن جعفر بن عبد الواحد بن أبي عون قال: فتزوجها عبيدة"),
 ]),

 "Umm Ḥabība (Ramla)": ("IbnSad", [
  ("Her name was Ramla, daughter of Abū Sufyān; her mother Ṣafiyya bt. Abī al-ʿĀṣ was ʿUthmān's aunt.",
   "واسمها رملة بنت أبي سفيان بن حرب بن أمية بن عبد شمس وأمها صفية بنت أبي العاص بن أمية بن عبد شمس، عمة عثمان بن عفان"),
  ("She had married ʿUbayd Allāh b. Jaḥsh and bore him Ḥabība, from whom she took her kunya.",
   "فولدت له حبيبة فكنيت بها فتزوج حبيبة داود بن عروة بن مسعود الثقفي"),
  ("He took her to Abyssinia in the second migration, became a Christian and left Islam, and died there — she held to her religion and her migration.",
   "وكان عبيد الله بن جحش هاجر بأم حبيبة معه إلى أرض الحبشة في الهجرة الثانية فتنصر وارتد عن الإسلام وتوفي بأرض الحبشة وثبتت أم حبيبة على دينها الإسلام وهجرتها"),
  ("The Prophet sent ʿAmr b. Umayya al-Ḍamrī to the Negus to ask for her; the Negus married her to him and paid her dower himself, four hundred dīnārs.",
   "بعث رسول الله صلى الله عليه وسلم عمرو بن أمية الضمري إلى النجاشي فخطب عليه أم حبيبة بنت أبي سفيان وكانت تحت عبيد الله بن جحش فزوجها إياه وأصدقها النجاشي من عنده عن رسول الله صلى الله عليه وسلم أربع مئة دينار"),
  ("When her father Abū Sufyān died she called for perfume and rubbed it on her arms and cheeks, saying she had no need of it — but she had heard the Prophet forbid a woman to mourn beyond three days.",
   "أن أم حبيبة زوج النبي صلى الله عليه وسلم لما مات أبوها أبو سفيان دعت بطيب فطلت به ذراعيها وعارضيها ثم قالت: إني كنت عن هذا لغنية"),
 ]),

 "Zaynab bt. Jaḥsh": ("IbnSad", [
  ("Her mother was Umayma bt. ʿAbd al-Muṭṭalib, so she was the Prophet's cousin; she migrated with him to Medina, and was a beautiful woman.",
   "وكانت زينب بنت جحش ممن هاجر مع رسول الله صلى الله عليه وسلم إلى المدينة وكانت امرأة جميلة"),
  ("The Prophet first asked for her on behalf of Zayd b. Ḥāritha; she refused — I am the unmarried woman of Quraysh, I do not accept him for myself.",
   "فخطبها رسول الله صلى الله عليه وسلم على زيد بن حارثة فقالت: يا رسول الله لا أرضاه لنفسي وأنا أيم قريش"),
  ("He said: I accept him for you. And she married Zayd.",
   "قال: فإني قد رضيته لك فتزوجها زيد بن حارثة"),
  ("The verse of the curtain came down over his own wedding to her, when the guests would not leave.",
   "فانطلق حتى دخل البيت فذهبت أدخل، فقال: بالباب بيني وبينه، ونزل الحجاب ووعظ القوم بما وعظوا به"),
  ("The wives asked which of them would follow him soonest. He said: the longest of you in the arm.",
   "سأل النسوة رسول الله صلى الله عليه وسلم أينا أسرع بك لحوقا؟ قال: أطولكن يدا"),
  ("ʿĀʾisha: we used to stretch our arms against the wall to measure — until Zaynab died, and she was a short woman, and we understood he had meant giving.",
   "فكنا إذا اجتمعنا في بيت إحدانا بعد النبي صلى الله عليه وسلم نمد أيدينا في الجدار نتطاول فلم نزل نفعل ذلك حتى توفيت زينب بنت جحش وكانت امرأة قصيرة"),
  ("She worked with her hands, and when she died they knew hers had been the longest arm in charity.",
   "فلما توفيت زينب علمن أنها كانت أطولهن يدا في الخير والصدقة"),
 ]),

 "Juwayriya bt. al-Ḥārith": ("IbnSad", [
  ("Daughter of al-Ḥārith b. Abī Ḍirār, of Banū al-Muṣṭaliq of Khuzāʿa.",
   "جويرية بنت الحارث بن أبي ضرار بن حبيب بن عائذ بن مالك بن جذيمة"),
  ("She had been married to Musāfiʿ b. Ṣafwān, who was killed on the day of al-Muraysīʿ.",
   "وهو المصطلق من خزاعة تزوجها مسافع بن صفوان ذي الشفر بن سرح بن مالك بن جذيمة فقتل يوم المريسيع"),
  ("When the Prophet married her the news went out and the people said: the Messenger of God's kin by marriage, held as slaves —",
   "وخرج الخبر إلى الناس فقالوا: أصهار رسول الله صلى الله عليه وسلم يسترقون"),
  ("and they freed the captives of Banū al-Muṣṭaliq in their hands, a hundred households.",
   "فأعتقوا ما كان في أيديهم من سبي بلمصطلق فبلغ عتقهم مئة أهل بيت بتزويجه إياها"),
  ("Ibn Saʿd: I know of no woman who was a greater blessing to her people than she was.",
   "فلا أعلم امرأة أعظم بركة على قومها منها، وذلك منصرفه من غزوة المريسيع"),
  ("She died in Rabīʿ al-Awwal of the year fifty-six, and Marwān b. al-Ḥakam, governor of Medina, prayed over her.",
   "توفيت جويرية بنت الحارث زوج النبي صلى الله عليه وسلم في شهر ربيع الأول سنة ست وخمسين في خلافة معاوية بن أبي سفيان وصلى عليها مروان بن الحكم"),
 ]),

 "Maymūna bt. al-Ḥārith": ("IbnSad", [
  ("Sister, by both parents, of Umm al-Faḍl bt. al-Ḥārith, and it was al-ʿAbbās who had charge of her affair.",
   "إياها العباس بن عبد المطلب، وكان يلي أمرها وهي أخت أم ولده أم الفضل بنت الحارث الهلالية لأبيها وأمها"),
  ("He married her at Sarif, ten miles from Mecca, in the year seven, on the ʿumra of the settlement — the last woman he married.",
   "وتزوجها رسول الله صلى الله عليه وسلم بسرف على عشرة أميال من مكة وكانت آخر امرأة تزوجها رسول الله صلى الله عليه وسلم وذلك سنة سبع في عمرة القضية"),
  ("She put her affair in his hands, and he went to al-ʿAbbās's house and asked him for her.",
   "وجعلت ميمونة أمرها إلى رسول الله صلى الله عليه وسلم فجاء رسول الله صلى الله عليه وسلم منزل العباس فخطبها إلى العباس فزوجها إياه"),
  ("Whether he was in iḥrām when he married her is a question the chapter puts directly to a witness.",
   None),
  ("Maymūn b. Mihrān asked Ṣafiyya bt. Shayba, an old woman by then: did he marry Maymūna while in iḥrām? She said: no, by God — he married her and they were both out of it.",
   "أتزوج رسول الله صلى الله عليه وسلم ميمونة، وهو محرم؟ فقالت: لا والله لقد تزوجها وإنهما لحلالان"),
  ("She died at Sarif, where she had been married, and Ibn ʿAbbās told them not to shake her bier.",
   "توفيت ميمونة بسرف فخرجنا مع ابن عباس إليها، فقال: إذا رفعتم نعشها فلا تزعزعوها ولا تزلزلوها"),
  ("He added a count of his own: the Prophet had nine wives, and allotted turns to eight of them, and to one he did not.",
   "فإنه كان للنبي صلى الله عليه وسلم تسع نسوة كان يقسم لثمان ولا يقسم لواحدة"),
 ]),

 "Ṭalḥa b. ʿUbayd Allāh": ("IbnSad", [
  ("Called Abū Muḥammad; his mother was al-Ṣaʿba bt. ʿAbd Allāh al-Ḥaḍramī.",
   "ويكنى أبا محمد. وأمه الصعبة بنت عبد الله بن عماد الحضرمي"),
  ("Her mother's father, Wahb b. ʿAbd, had held the provisioning of the pilgrims for all Quraysh.",
   "وأمها عاتكة بنت وهب بن عبد بن قصي بن كلاب، وكان وهب بن عبد صاحب الرفادة دون قريش كلها"),
  ("He came to Islam through what a monk had told him: Abū Bakr took him in to the Prophet, who was gladdened by the report.",
   "فأخبره طلحة بما قال الراهب, فخرج أبو بكر بطلحة, فدخل به على رسول الله صلى الله عليه وسلم, فأسلم طلحة، وأخبر رسول الله بما قال الراهب، فسر رسول الله صلى الله عليه وسلم بذلك"),
  ("Nawfal b. Khuwaylid bound him and Abū Bakr in a single rope, and Banū Taym did not stop him.",
   "فلما أسلم أبو بكر, وطلحة بن عبيد الله, أخذهما نوفل بن خويلد بن العدوية, فشدهما في حبل واحد، ولم يمنعهما بنو تيم"),
  ("Abū Bakr's account of Uḥud: I was among the first to return, and the Messenger of God said to us — see to your companion, meaning Ṭalḥa.",
   "قالت: حدثني أبو بكر قال: كنت في أول من فاء إلى رسول الله صلى الله عليه وسلم يوم أحد، فقال لنا رسول الله صلى الله عليه وسلم: عليكم صاحبكم، يريد طلحة"),
  ("ʿUmar once saw him in iḥrām wearing two garments dyed with red ochre, and asked him what he meant by them.",
   "أن عمر رأى على طلحة بن عبيد الله ثوبين مصبوغين بمشق، وهو محرم فقال: ما بال هذين الثوبين يا طلح؟"),
  ("His son Muḥammad, called al-Sajjād, was killed with him on the day of the Camel.",
   "وكان لطلحة من الولد: محمد، وهو السجاد، وبه كان يكنى، قتل يوم الجمل مع أبيه"),
 ]),

 "al-Zubayr b. al-ʿAwwām": ("IbnSad", [
  ("His mother was Ṣafiyya bt. ʿAbd al-Muṭṭalib, so he was the Prophet's cousin.",
   "وأمه صفية بنت عبد المطلب بن هاشم بن عبد مناف بن قصي"),
  ("He was called Abū ʿAbd Allāh.",
   "أن الزبير بن العوام كان يكنى أبا عبد الله"),
  ("He had eleven sons and nine daughters.",
   "وكان للزبير من الولد أحد عشر ذكرا وتسع نسوة"),
  ("When he broke a boy's hand as a child and they brought the complaint to his mother, she answered in verse — asking how they had found Zubayr.",
   "قال: وكسر يد غلام ذات يوم، فجيء بالغلام إلى صفية، وقيل لها ذلك، فقالت صفية: كيف وجدت زبرا"),
  ("Hishām b. ʿUrwa: he entered Islam at sixteen, and never stayed behind from a raid the Prophet made.",
   "أن الزبير أسلم وهو ابن ست عشرة سنة، ولم يتخلف عن غزوة غزاها رسول الله صلى الله عليه وسلم"),
  ("At Badr he wore a yellow turban wound about his head — and the angels that day, it is said, wore yellow turbans.",
   "كان على الزبير يوم بدر عمامة صفراء معتجرا بها، وكانت على الملائكة يومئذ عمائم صفر"),
  ("He was at Badr, Uḥud and every engagement, held his ground at Uḥud and pledged himself to death, and carried one of the three Muhājir banners at the Conquest.",
   "وشهد الزبير بن العوام بدرا، وأحدا, والمشاهد كلها مع رسول الله صلى الله عليه وسلم، وثبت معه يوم أحد, وبايعه على الموت، وكانت مع الزبير إحدى رايات المهاجرين الثلاث في غزوة الفتح"),
 ]),

 "ʿAbd al-Raḥmān b. ʿAwf": ("IbnSad", [
  ("In the Jāhiliyya his name was ʿAbd ʿAmr; the Prophet named him ʿAbd al-Raḥmān when he entered Islam. He was called Abū Muḥammad.",
   "وكان اسمه في الجاهلية: عبد عمرو, فسماه رسول الله صلى الله عليه وسلم حين أسلم: عبد الرحمن, ويكنى أبا محمد"),
  ("His mother was al-Shifāʾ bt. ʿAwf, of Zuhra — his father's clan as well.",
   "وأمه الشفاء بنت عوف بن عبد بن الحارث بن زهرة بن كلاب"),
  ("He was born ten years after the Elephant.",
   "قال: ولد عبد الرحمن بن عوف بعد الفيل بعشر سنين"),
  ("He entered Islam before the Prophet went into the house of al-Arqam, and before he began calling people there.",
   "قال: أسلم عبد الرحمن بن عوف قبل أن يدخل رسول الله صلى الله عليه وسلم دار الأرقم بن أبي الأرقم، وقبل أن يدعو فيها"),
  ("He said the Prophet had marked out land for him in Syria called al-Salīl, and died before writing him any document for it.",
   "قال عبد الرحمن بن عوف: قطع لي رسول الله صلى الله عليه وسلم أرضا بالشام, يقال لها: السليل، فتوفي النبي صلى الله عليه وسلم ولم يكتب لي بها كتابا"),
  ("His eldest son, Sālim, died before Islam.",
   "وكان لعبد الرحمن بن عوف من الولد سالم الأكبر, مات قبل الإسلام"),
 ]),

 "Saʿīd b. Zayd": ("IbnSad", [
  ("Called Abū al-Aʿwar; his line runs back through Nufayl to ʿAdī b. Kaʿb — the same stock as ʿUmar.",
   "بن عمرو بن نفيل بن عبد العزى بن رياح بن عبد الله بن قرط بن رزاح بن عدي بن كعب بن لؤي, ويكنى أبا الأعور"),
  ("His mother was Fāṭima bt. Baʿja, of Khuzāʿa.",
   "وأمه فاطمة بنت بعجة بن أمية بن خويلد بن خالد بن المعمر بن حيان بن غنم بن مليح من خزاعة"),
  ("His father Zayd b. ʿAmr went looking for a religion — travelled to Syria and asked the Jews and the Christians, and was not satisfied by what they had.",
   "وكان أبوه زيد بن عمرو بن نفيل يطلب الدين، وقدم الشام فسأل اليهود والنصارى عن العلم والدين فلم يعجبه دينهم"),
  ("A Christian told him: what you are after is the religion of Ibrāhīm. And Zayd asked: what is the religion of Ibrāhīm?",
   "فقال له رجل من النصارى: أنت تلتمس دين إبراهيم، فقال زيد: وما دين إبراهيم؟"),
  ("Zayd died before the message came, and was buried at the foot of Ḥirāʾ.",
   "قال: مات زيد بن عمرو فدفن بأصل حراء"),
  ("His son entered Islam before the Prophet went into the house of al-Arqam, and before he began calling people there.",
   "قال: أسلم سعيد بن زيد بن عمرو بن نفيل قبل أن يدخل رسول الله صلى الله عليه وسلم دار الأرقم، وقبل أن يدعو فيها"),
 ]),

 "Abū ʿUbayda b. al-Jarrāḥ": ("IbnSad", [
  ("His name was ʿĀmir b. ʿAbd Allāh b. al-Jarrāḥ, of Fihr.",
   "واسمه عامر بن عبد الله بن الجراح بن هلال بن أهيب بن ضبة بن الحارث بن فهر"),
  ("His two sons died and left nothing, so he has no line.",
   "فدرج ولد أبي عبيدة بن الجراح، فليس له عقب"),
  ("He entered Islam with ʿUthmān b. Maẓʿūn and ʿAbd al-Raḥmān b. ʿAwf, before the Prophet went into the house of al-Arqam.",
   "قال: أسلم أبو عبيدة بن الجراح مع عثمان بن مظعون, وعبد الرحمن بن عوف وأصحابهم قبل دخول رسول الله صلى الله عليه وسلم دار الأرقم"),
  ("He was at Badr and Uḥud, and held his ground at Uḥud when the people were routed and turned.",
   "وشهد أبو عبيدة بدرا، وأحدا, وثبت يوم أحد مع رسول الله صلى الله عليه وسلم حين انهزم الناس وولوا"),
  ("He was at the Trench and every engagement, one of the foremost of the Companions, and was sent to Dhū al-Qaṣṣa with forty men.",
   "وشهد أبو عبيدة الخندق, والمشاهد كلها مع رسول الله صلى الله عليه وسلم، وكان من علية أصحابه، وبعثه رسول الله صلى الله عليه وسلم إلى ذي القصة سرية في أربعين رجلا"),
  ("When a man said under his siege that things would not be so hard had it been Khālid b. al-Walīd, Muʿādh answered him sharply.",
   "بلغني أن معاذ بن جبل سمع رجلا يقول: لو كان خالد بن الوليد ما كان بالناس دوك، وذلك في حصر أبي عبيدة بن الجراح"),
  ("ʿIrbāḍ b. Sāriya went in to him as he was dying, and heard him say: God forgive ʿUmar b. al-Khaṭṭāb for turning back from Sargh.",
   "دخلت على أبي عبيدة بن الجراح في مرضه الذي مات فيه وهو يموت، فقال: غفر الله لعمر بن الخطاب رجوعه من سرغ"),
 ]),

 "Saʿd b. Muʿādh": ("IbnSad", [
  ("Of ʿAbd al-Ashhal of al-Aws, and called Abū ʿAmr.",
   "بن امرئ القيس بن زيد بن عبد الأشهل, ويكنى أبا عمرو"),
  ("His mother Kabsha bt. Rāfiʿ was of al-Khazraj, and among the women who gave the pledge.",
   "وأمه كبشة بنت رافع بن معاوية بن عبيد بن الأبجر، وهو خدرة بن عوف بن الحارث بن الخزرج، وهي من المبايعات"),
  ("He married his brother Aws's widow, Hind bt. Simāk — the aunt of Usayd b. Ḥuḍayr.",
   "خلف عليها سعد بعد أخيه أوس بن معاذ، وهي عمة أسيد بن حضير بن سماك"),
  ("Ibn Isḥāq, alone, pairs him in brotherhood with Abū ʿUbayda; Ibn Saʿd leaves it open.",
   "قال: وأما محمد بن إسحاق فقال: آخى رسول الله صلى الله عليه وسلم بين سعد بن معاذ, وأبي عبيدة بن الجراح، فالله أعلم أي ذلك كان"),
  ("The banner of al-Aws at Badr was his; he was at Uḥud and held his ground when the people turned, and at the Trench.",
   "كان لواء الأوس يوم بدر مع سعد بن معاذ، وشهد سعد مع رسول الله صلى الله عليه وسلم يوم أحد, وثبت معه حين ولى الناس، وشهد الخندق"),
  ("The Prophet slept, and an angel — or Jibrīl — came to him as he woke and asked: which man of your community died tonight, whose death the people of heaven rejoiced at?",
   "فنام رسول الله صلى الله عليه وسلم, فأتاه ملك, أو قال: جبريل حين استيقظ، فقال: من رجل من أمتك مات الليلة، استبشر بموته أهل السماء؟"),
  ("His mother wept over him in verse, and the Prophet said: every wailing woman lies but Umm Saʿd.",
   "وأمه تبكيه وهي تقول: ويل أم سعد سعدا حزامة وجدا فقال رسول الله صلى الله عليه وسلم: كل نائحة تكذب إلا أم سعد"),
  ("Those carrying him said they had never carried a body lighter; he answered that so many angels had come down for it.",
   "يا رسول الله، ما حملنا ميتا أخف علينا من سعد، فقال: وما يمنعه من أن يخف عليكم، وقد هبط من الملائكة كذا وكذا"),
 ]),

 "Muʿādh b. Jabal": ("IbnSad", [
  ("Of Banū Salima of al-Khazraj; his mother Hind bt. Sahl was of Juhayna.",
   "وأمه هند بنت سهل من جهينة, ثم من بني الربعة، وأخوه لأمه عبد الله بن الجد بن قيس من أهل بدر"),
  ("Called Abū ʿAbd al-Raḥmān; he was at al-ʿAqaba with the seventy of the Anṣār,",
   "ويكنى معاذ أبا عبد الرحمن، وشهد العقبة في روايتهم جميعا مع السبعين من الأنصار"),
  ("and when he entered Islam he went about breaking the idols of Banū Salima with Thaʿlaba b. ʿAnama and ʿAbd Allāh b. Unays.",
   "وكان معاذ بن جبل لما أسلم يكسر أصنام بني سلمة هو وثعلبة بن عنمة, وعبد الله بن أنيس"),
  ("Ibn Saʿd: the pairing with Ibn Masʿūd is not disputed among us — Ibn Isḥāq alone gives another.",
   "آخى رسول الله صلى الله عليه وسلم بين معاذ بن جبل, وعبد الله بن مسعود، لا اختلاف فيه عندنا"),
  ("He was at Badr at twenty, or twenty-one, and at Uḥud, the Trench and every engagement.",
   "وشهد معاذ بدرا، وهو ابن عشرين أو إحدى وعشرين سنة"),
  ("When the Prophet died, Muʿādh was his governor over al-Janad.",
   "قال: توفي رسول الله صلى الله عليه وسلم وعامله على الجند معاذ بن جبل"),
  ("Abū Idrīs al-Khawlānī: I entered the mosque of Damascus and there was a young man with shining teeth, and people around him who referred every disagreement to him and left it at his opinion.",
   "دخلت مسجد دمشق فإذا فتى براق الثنايا، وإذا ناس معه, إذا اختلفوا في شيء أسندوه إليه وصدروا عن رأيه"),
 ]),

 "Ubayy b. Kaʿb": ("IbnSad", [
  ("Of Banū al-Najjār of al-Khazraj, and called Abū al-Mundhir.",
   "ابن قيس بن عبيد بن زيد بن معاوية بن عمرو بن مالك بن النجار, ويكنى أبا المنذر"),
  ("His mother was Ṣuhayla bt. al-Aswad, of Banū Mālik b. al-Najjār.",
   "وأمه صهيلة بنت الأسود بن حرام بن عمرو, من بني مالك بن النجار"),
  ("Ibn Saʿd gathers several reports of the day of his death, each carrying the same sentence:",
   None),
  ("the lord of the Muslims died today, Ubayy b. Kaʿb.",
   "قال: قلت: أجل، قالوا: مات سيد المسلمين أبي بن كعب"),
  ("One who heard it remarked that he had never seen a man so covered over as this man had been.",
   "قلت: والله إن رأيت كاليوم في الستر أشد مما ستر هذا الرجل"),
  ("Ibn Saʿd weighs the reports himself: these say he died under ʿUmar, and his family put it at twenty-two — but the year thirty, under ʿUthmān, is the soundest of the accounts to us.",
   "هذه الأحاديث في موت أبي تدل (1) على أنه مات في خلافة عمر بن الخطاب رضي الله عنه، فيما رأيت أهله وغير واحد من أصحابنا يقولون: سنة ثنتين وعشرين بالمدينة، وقد سمعت من يقول: مات في خلافة عثمان بن عفان رضي الله عنه, سنة ثلاثين، وهو أثبت هذه الأقاويل عندنا"),
 ]),

 "Usayd b. Ḥuḍayr": ("IbnSad", [
  ("Of ʿAbd al-Ashhal of al-Aws; called Abū Yaḥyā, and also Abū al-Ḥuḍayr.",
   "ابن سماك بن عتيك بن امرئ القيس بن زيد بن عبد الأشهل, ويكنى أبا يحيى, وكان يكنى أيضا أبا الحضير"),
  ("His mother's name comes down two ways: Umm Usayd bt. al-Nuʿmān on Muḥammad b. ʿUmar's authority,",
   "وأمه في رواية محمد بن عمر: أم أسيد بنت النعمان بن امرئ القيس بن زيد بن عبد الأشهل"),
  ("and Umm Usayd bt. Sakan on ʿAbd Allāh b. Muḥammad's.",
   "وفي رواية عبد الله بن محمد بن عمارة الأنصاري: أم أسيد بنت سكن بن كرز بن زعوراء بن عبد الأشهل"),
  ("His father Ḥuḍayr of the Squadrons was a chief in the Jāhiliyya and led al-Aws at Buʿāth — the last battle between al-Aws and al-Khazraj — and was killed there.",
   "وكان أبوه حضير الكتائب شريفا في الجاهلية, وكان رئيس الأوس يوم بعاث, وهي آخر وقعة كانت بين الأوس والخزرج في الحروب التي كانت بينهم، وقتل يومئذ حضير الكتائب"),
  ("Ibn Saʿd dates that battle by the Prophet: it happened while he was at Mecca, already prophesying and calling to Islam, and he migrated six years after it.",
   "وكانت هذه الوقعة ورسول الله صلى الله عليه وسلم بمكة قد تنبأ, ودعا إلى الإسلام"),
  ("He took seven wounds at Uḥud and held his ground when the people broke, and was at the Trench and every engagement.",
   "وشهد أسيد أحدا, وجرح يومئذ سبع جراحات، وثبت مع رسول الله صلى الله عليه وسلم حين انكشف الناس، وشهد الخندق والمشاهد كلها"),
  ("He died in Shaʿbān of the year twenty, and ʿUmar himself carried his bier out of Banū ʿAbd al-Ashhal to al-Baqīʿ and prayed over him there.",
   "توفي أسيد بن الحضير في شعبان سنة عشرين، فحمله عمر بن الخطاب بين العمودين من بني عبد الأشهل حتى وضعه بالبقيع، وصلى عليه بالبقيع"),
 ]),

 "Hāshim": ("IbnSad", [
  ("Ibn ʿAbbās: Hāshim's name was ʿAmr, and he was the man of the Īlāf of Quraysh.",
   "قال: كان اسم هاشم عمرا، وكان صاحب إيلاف قريش"),
  ("He was the first to appoint Quraysh their two journeys — one in winter to the Yemen and to the Negus in Abyssinia, and one in summer to Syria.",
   "وكان أول من سن الرحلتين لقريش، ترحل إحداهما في الشتاء إلى اليمن، وإلى الحبشة إلى النجاشي فيكرمه ويحبوه، ورحلة في الصيف إلى الشام"),
  ("Ibn Saʿd names his children by their mothers, one of whom, Qayla, was nicknamed the Slaughter-Camel and was of Khuzāʿa.",
   "وأمه قيلة، وكانت تلقب الجزور بنت عامر بن مالك بن جذيمة، وهو المصطلق من خزاعة"),
  ("His kunya is disputed: Abū Yazīd, or, some say, after his son Asad.",
   "قال: وكان هاشم يكنى أبا يزيد، وقال بعضهم: بل كان يكنى بابنه أسد بن هاشم"),
  ("When he died his children mourned him in a great deal of verse, and Ibn Saʿd notes that his daughter Khālida's elegy is weak poetry.",
   "ولما توفي هاشم رثاه ولده بأشعار كثيرة، فكان مما قيل فيما أخبرنا محمد بن عمر عن رجاله قالت خالدة بنت هاشم ترثي أباها وهو شعر فيه ضعف"),
 ]),

 "ʿAbd al-Muṭṭalib": ("IbnSad", [
  ("The chapter opens on his uncle: al-Muṭṭalib, whom Quraysh called the Overflowing for his openhandedness, and who held the watering and provisioning after Hāshim.",
   "كان المطلب بن عبد مناف بن قصي أكبر من هاشم ومن عبد شمس وهو الذي عقد الحلف لقريش من النجاشي في متجرها، وكان شريفا في قومه مطاعا سيدا، وكانت قريش تسميه الفيض لسماحته فولي بعد هاشم السقاية والرفادة"),
  ("Digging where he was told — by the dung, by the ants, by the sitting-place of Khuzāʿa — he found a gazelle, weapons and gold.",
   "احتفر عند الفرث عند النمل عند مجلس خزاعة ونحوه، فاحتفر فوجد غزالا وسلاحا وأظفارا"),
  ("His people crowded him over the find, and it was then that he vowed that if ten sons were born to him he would sacrifice one.",
   "فقال قومه لما رأوا الغنيمة كأنهم يريدون أن يغازوه قال: فعند ذلك نذر لئن ولد له عشرة لينحرن أحدهم"),
  ("When ten were born and he meant to slaughter ʿAbd Allāh, Banū Zuhra stopped him and told him to cast lots.",
   "فلما ولد له عشرة وأراد ذبح عبد الله منعته بنو زهرة، وقالوا: أقرع بينه"),
  ("Ibn ʿAbbās: the blood-price then was ten camels, and ʿAbd al-Muṭṭalib was the first to set it at a hundred — Quraysh and the Arabs followed him, and the Prophet left it as it stood.",
   "قال: كانت الدية يومئذ عشرا من الإبل وعبد المطلب أول من سن دية النفس مائة من الإبل فجرت في قريش والعرب مائة من الإبل وأقرها رسول الله صلى الله عليه وسلم على ما كانت عليه"),
  ("He was the first of Quraysh at Mecca to dye with wasma, after a Ḥimyarī notable asked him whether he would like to be rid of the white and be young again.",
   "كان أول من خضب بالوسمة من قريش بمكة عبد المطلب بن هاشم فكان إذا ورد اليمن نزل على عظيم من عظماء حمير فقال له: يا عبد المطلب هل لك أن تغير هذا البياض فتعود شابا؟"),
  ("On a journey his water ran out and Thaqīf refused him; a spring broke open under his camel's chest, and when their own water failed he gave them to drink.",
   "ففجر الله لهم عينا من تحت جران بعير عبد المطلب, فحمد الله عز وجل، وعلم أن ذلك منة، فشربوا ريهم، وحملوا حاجتهم ونفد ماء الثقفيين فبعثوا إلى عبد المطلب يستسقونه فسقاهم"),
  ("He had twelve sons and six daughters; the eldest, al-Ḥārith, whose name gave him his kunya, died in his father's lifetime.",
   "ولد عبد المطلب بن هاشم بن عبد مناف اثني عشر رجلا وست نسوة: الحارث وهو أكبر ولده, وبه كان يكنى ومات في حياة أبيه"),
 ]),

 "Ādam": ("IbnSad", [
  ("Ibn Saʿd's chapter here is Ḥawwāʾ's, and it is barely a page. Mujāhid on 'and He created from it its mate': Ḥawwāʾ was created from Ādam's shortest rib while he slept.",
   "قال: خلق حواء من قصيرى آدم صلى الله عليه وسلم، والقصيرى الضلع الأقصر، وهو نائم"),
  ("He woke and said athā — woman, in Nabataean.",
   "فاستيقظ، فقال: أثا، امرأة بالنبطية"),
  ("Ibn ʿAbbās: she was called Ḥawwāʾ because she is the mother of every living thing.",
   "قال: إنما سميت حواء لأنها أم كل حي"),
 ]),

 "Nūḥ": ("IbnSad", [
  ("Ibn ʿAbbās gives the ages plainly: Lamak was eighty-two when Nūḥ was born.",
   "قال: كان للمك يوم ولد نوحا اثنتان وثمانون سنة"),
  ("Nobody in that age forbade wrong, so God sent Nūḥ to them when he was four hundred and eighty.",
   "ولم يكن أحد في ذلك الزمان ينهى عن منكر، فبعث الله نوحا إليهم، وهو ابن أربع مئة وثمانين سنة"),
  ("He called them for a hundred and twenty years, then was ordered to build the ship, and he built it and rode in it at six hundred.",
   "ثم دعاهم في نبوته مئة وعشرين سنة، ثم أمره بصنعة السفينة، فصنعها وركبها وهو ابن ست مئة سنة"),
  ("Saʿīd b. al-Musayyab: Nūḥ had three sons — Sām, Ḥām and Yāfith.",
   "قال: ولد نوح ثلاثة: سام، وحام، ويافث"),
  ("The chapter is really a table of the nations: the Arabs, the Persians and the Byzantines from Sām, and so on through the rest.",
   "فولد سام العرب وفارس والروم، وفي كل هؤلاء خير، وولد حام السودان والبربر والقبط، وولد يافث الترك والصقالبة ويأجوج ومأجوج"),
  ("Ibn ʿAbbās again: the Arabs, the Persians, the Nabateans, the people of India and Sind are of the children of Sām b. Nūḥ.",
   "قال ابن عباس: والعرب والفرس والنبط والهند والسند والبند من ولد سام بن نوح"),
  ("It is said ʿImlīq was the first to speak Arabic when they left Babel, and that he and Jurhum were called the Arabising Arabs.",
   "ويقال: إن عمليق أول من تكلم بالعربية حين ظعنوا من بابل، وكان يقال لهم ولجرهم: العرب العاربة"),
 ]),

 "Ibrāhīm (khalīl Allāh)": ("IbnSad", [
  ("al-Kalbī: Ibrāhīm's father was of the people of Ḥarrān, and a year of drought drove him to Hurmuzjird with his wife.",
   "قال: كان أبو إبراهيم من أهل حران فأصابته سنة، فأتى هرمزجرد ومعه امرأته أم إبراهيم"),
  ("Her name is given as Nūnā bt. Karnabā,",
   "واسمها نونا بنت كرنبا بن كوثى من بني أرفخشذ بن سام بن نوح"),
  ("and, on other authority, as Abyūnā of the line of Afrāyim.",
   "قال: اسمها أبيونا من ولد أفرايم بن أرغوا بن فالغ بن عابر بن شالخ بن أرفخشد بن سام بن نوح"),
  ("He was the first to take in a guest, the first to crumble bread into broth, and the first to see grey hair.",
   "وهو أول من أضاف الضيف، وأول من ثرد الثريد، وأول من رأى الشيب"),
  ("ʿIkrima: Ibrāhīm was called the father of guests.",
   "قال: كان إبراهيم خليل الرحمن صلى الله عليه وسلم يكنى أبا الأضياف"),
  ("Abū Hurayra: he was circumcised with an adze at a hundred and twenty, and lived eighty years after it.",
   "قال: اختتن إبراهيم بالقدوم وهو ابن عشرين ومئة سنة، ثم عاش بعد ذلك ثمانين سنة"),
  ("Ismāʿīl was born to him, and was his eldest.",
   "قال: ولد لإبراهيم صلى الله عليه وسلم إسماعيل، وهو أكبر ولده"),
 ]),

 "Ismāʿīl": ("IbnSad", [
  ("Hājar was a Copt, from a village near what is now the encampment of Egypt, and belonged to a Pharaoh.",
   "قالوا: كانت هاجر من القبط، من قرية أمام الفرما، قريب من فسطاط مصر، وكانت لفرعون من الفراعنة"),
  ("It was that Pharaoh who reached for Sāra and was struck down — or, it is said, his hand withered to his chest as he went to take hers.",
   "وهو الذي عرض لسارة امرأة إبراهيم فصرع، ويقال: بل ذهب يتناول يدها فيبست يده إلى صدره"),
  ("God commanded Ibrāhīm to go to His sacred land; he rode al-Burāq with Ismāʿīl, then two years old, before him and Hājar behind.",
   "أوحى الله إلى إبراهيم يأمره بالمسير إلى بلده الحرام، فركب إبراهيم البراق، وحمل إسماعيل أمامه وهو ابن سنتين، وهاجر خلفه"),
  ("Who first spoke Arabic is asked outright, and answered three ways in three consecutive reports.",
   None),
  ("Muḥammad b. ʿAlī: Ismāʿīl, at thirteen.",
   "قال: إسماعيل بن إبراهيم صلى الله عليهما، وهو ابن ثلاث عشرة سنة"),
  ("Others: he was inspired with the tongue of the Arabs from the day he was born, and all Ibrāhīm's other children spoke their father's tongue.",
   "أن إسماعيل ألهم من يوم ولد لسان العرب، وولد إبراهيم أجمعون على لسان أبيهم"),
  ("al-Kalbī, flatly against both: Ismāʿīl did not speak Arabic and would not differ from his father — the first of his descendants to speak it were the sons of Raʿla bt. Yashjub.",
   "قال: لم يتكلم إسماعيل بالعربية، ولم يستحل خلاف أبيه، وأول من تكلم بالعربية من ولده بنو رعلة بنت يشجب"),
 ]),

 "ʿAdnān": ("IbnSad", [
  ("Hishām al-Kalbī opens: my father taught me the Prophet's lineage when I was a boy — and recites it down through the epithets.",
   "قال: علمني أبي وأنا غلام نسب النبي صلى الله عليه وسلم: محمد الطيب المبارك ابن عبد الله بن عبد المطلب، واسمه شيبة الحمد بن هاشم، واسمه عمرو بن عبد مناف"),
  ("A man of Tadmur who had read the books of the Children of Israel reported that Bārūkh, Jeremiah's scribe, had written down the line of Maʿadd b. ʿAdnān, and that the rabbis knew it.",
   "وكان رجل من أهل تدمر يكنى أبا يعقوب، من مسلمة بني إسرائيل، قد قرأ من كتبهم، وعلم علمهم، فذكر أن بورخ بن ناريا كاتب أرميا أثبت نسب معد بن عدنان عنده"),
  ("Ibn Saʿd then gives his own verdict, and it is the reason this site stops where it does.",
   None),
  ("I have seen no disagreement among them that Maʿadd is of the children of Qaydar b. Ismāʿīl. This disagreement about his descent shows that it was not preserved — it was taken from the People of the Book and translated for them, and they differed over it.",
   "ولم أر بينهم اختلافا أن معدا من ولد قيذر بن إسماعيل، وهذا الاختلاف في نسبته يدل على أنه لم يحفظ، وإنما أخذ ذلك من أهل الكتاب، وترجموه لهم فاختلفوا فيه"),
  ("And had it been sound, the Messenger of God would have known it best of anyone. So the matter with us ends at Maʿadd.",
   "ولو صح ذلك لكان رسول الله صلى الله عليه وسلم أعلم الناس به، فالأمر عندنا على الانتهاء إلى معد"),
  ("The Prophet, in the same chapter: do not revile Muḍar, for he had submitted.",
   "قال رسول الله صلى الله عليه وسلم: لا تسبوا مضر، فإنه كان قد أسلم"),
 ]),

 "Quraysh (Fihr)": ("IbnSad", [
  ("Hishām al-Kalbī recites the line and stops at the name that defines the tribe.",
   None),
  ("Quraysh gather at Fihr — and whoever stands above Fihr is not called Qurashī.",
   "وإلى فهر جماع قريش، وما كان فوق فهر فليس يقال له قرشي"),
  ("Above him the line runs through Mālik, al-Naḍr, Kināna, Khuzayma and Mudrika to Maʿadd b. ʿAdnān, and there Ibn Saʿd stops.",
   "بن مرة بن كعب بن لؤي بن غالب بن فهر"),
  ("Of Maʿadd's sons, Nizār fathered Muḍar and Iyād — his kunya — by Sawda bt. ʿAkk, and Rabīʿa and Anmār by another mother.",
   "فولد نزار بن معد مضر، وإيادا، وبه كان يكنى نزار، وأمهما سودة بنت عك، وربيعة وهو الفرس وهو القشعم، وأنمارا"),
  ("Muḍar was called the Red, Iyād the Grey-and-Piebald.",
   "وكان يقال لمضر: الحمراء، ولإياد: الشمطاء والبلقاء"),
 ]),

 "Anas b. Mālik": ("IbnSad", [
  ("Of Banū al-Najjār of al-Khazraj; his mother was Umm Sulaym bt. Milḥān, of the same clan.",
   "وأمه أم سليم بنت ملحان بن خالد بن زيد بن حرام بن جندب بن عامر بن غنم بن عدي بن النجار، فولد أنس بن مالك: عبد الله"),
  ("Abū Ṭalḥa took his hand when the Prophet reached Medina: Messenger of God, Anas is a clever boy, let him serve you.",
   "أخذ أبو طلحة بيدي, فانطلق إلى رسول الله صلى الله عليه وسلم, فقال: يا رسول الله، إن أنسا غلام كيس فليخدمك"),
  ("His mother's version has her bring him herself: this is my son, and he is a boy who writes.",
   "أخذت أم سليم بيدي مقدم النبي صلى الله عليه وسلم، فأتت بي رسول الله صلى الله عليه وسلم, فقالت: يا رسول الله، هذا ابني، وهو غلام كاتب"),
  ("How long he served, and from what age, he tells differently in different reports.",
   None),
  ("I served the Prophet ten years, and he never once said uff to me.",
   "قال: خدمت النبي صلى الله عليه وسلم عشر سنين, فما قال لي أف قط"),
  ("I served him nine years, and he never said of anything I did: you did badly.",
   "قال أنس: فخدمته تسع سنين، فما قال لشيء صنعته قط أسأت"),
  ("I served the Messenger of God when I was eight years old.",
   "سمعت أنس بن مالك يقول: خدمت رسول الله صلى الله عليه وسلم وأنا ابن ثماني سنين"),
  ("And if any of the household blamed him, the Prophet would say: leave him — had it been decreed, it would have been.",
   "وإن لامني أحد من أهله, قال: دعوه، فلو قدر، أو قال: قضي أن يكون لكان"),
  ("His mother asked a prayer for him: God, increase his wealth and his children, lengthen his life and forgive his sin.",
   "فقالت: يا رسول الله, خويدمك ادع الله له، قال: اللهم أكثر ماله وولده وأطل عمره واغفر ذنبه"),
  ("Anas afterwards: I have buried a hundred of my own children bar two, and my palms bear twice a year.",
   "قال أنس: فقد دفنت من صلبي مئة غير اثنين، أو قال: مئة واثنين، وإن ثمرتي لتحمل في السنة مرتين"),
  ("He was the last Companion to die at Baṣra.",
   "قال: أنس بن مالك آخر من مات من أصحاب النبي صلى الله عليه وسلم بالبصرة"),
  ("His age at death is given as ninety-nine,",
   "وذكر لنا أنه كان يوم مات ابن تسع وتسعين سنة"),
  ("and Ibn Saʿd, asking the qāḍī Muḥammad b. ʿAbd Allāh al-Anṣārī outright, is told a hundred and seven.",
   "سألت محمد بن عبد الله الأنصاري القاضي: ابن كم كان أنس بن مالك يوم مات؟ قال: ابن مئة سنة وسبع سنين"),
 ]),

 "Rayḥāna bt. Zayd": ("IbnSad", [
  ("Of Banū al-Naḍīr, married to a man of Banū Qurayẓa called al-Ḥakam — which is why some transmitters assign her to Qurayẓa instead.",
   "من بني النضير وكانت متزوجة رجلا من بني قريظة يقال له الحكم فنسبها بعض الرواة إلى بني قريظة لذلك"),
  ("Thaʿlaba b. Abī Mālik: when the captives of Qurayẓa fell, the Messenger of God took her, freed her, married her, and she died with him.",
   "سباها رسول الله صلى الله عليه وسلم فأعتقها وتزوجها وماتت عنده"),
  ("Her own account: I was among those shown to him, and he had me set aside.",
   "فكنت فيمن عرض عليه فأمر بي فعزلت"),
  ("He said: if you choose God and His Messenger, then the Messenger of God chooses you for himself. And I said I choose God and His Messenger.",
   "فقال: إن اخترت الله ورسوله اختارك رسول الله صلى الله عليه وسلم لنفسه، فقلت: إني أختار الله ورسوله"),
  ("When I became Muslim he freed me and married me and gave me twelve ounces and a nashsh, as he gave his wives.",
   "فلما أسلمت أعتقني رسول الله صلى الله عليه وسلم وتزوجني وأصدقني اثنتي عشرة أوقية ونشا"),
  ("Muḥammad b. Kaʿb has it differently: she was of the spoil, and he gave her the choice between Islam and her own religion.",
   "كانت ريحانة مما أفاء الله عليه فكانت امرأة جميلة وسيمة فلما قتل زوجها وقعت في السبي"),
  ("In that account she grew violently jealous, he divorced her once, she wept, and he took her back.",
   "فغارت عليه غيرة شديدة فطلقها تطليقة وهي في موضعها لم تبرح فشق عليها وأكثرت البكاء"),
  ("Ibn Saʿd puts the marriage in Muḥarram of the year six; she remained with him until she died on his return from the Farewell Pilgrimage, and he buried her at al-Baqīʿ.",
   "فلم تزل عنده حتى ماتت مرجعه من حجة الوداع فدفنها بالبقيع، وكان تزويجه إياها في المحرم سنة ست من الهجرة"),
  ("The lists that count thirteen wives are the lists that leave her out.",
   None),
 ]),

}
